### PR TITLE
argp: Add argp-standalone

### PR DESCRIPTION
**Pull request by gonapps**
1. getopt(), getopt_long() cannot completely replace argp functionalities. (no builtin --help, --usage support)
2. perf uses libsubcmd(https://elixir.bootlin.com/linux/latest/source/tools/lib/subcmd/parse-options.h#L122) for parsing command line options
   which seems to have even smaller features than getopt, as you can see at https://elixir.bootlin.com/linux/latest/source/tools/perf/perf.c#L222
3. **Only left choice was argp-standalone 1.3**. Even though this project is almost dead (latest stable release 1.3 is at 2004),
but some of package managers(FreeBSD, Alpine, Gentoo) have argp-standalone,
and this is the only way to replace libc argp without large modification of current source.
this will add autotools as a build-time dependency.

Signed-off-by: Byeonggon Lee <gonny952@gmail.com>

----
@namhyung, @honggyukim 
This is currently WIP. But I just want to know if you are ok with this choice.

### CODE REVIEW

**Comment by gonapps** [comment]
Tried compiling on Android(Termux)..
Currently argp error is gone.
However there are more problems.
```console
/data/data/com.termux/files/home/uftrace/cmds/record.c:810:7: warning: implicit declaration of
      function 'shm_open' is invalid in C99 [-Wimplicit-function-declaration]
        fd = shm_open(sess_id, O_RDWR, 0600);
             ^
/data/data/com.termux/files/home/uftrace/cmds/record.c:926:4: warning: implicit declaration of
      function 'shm_unlink' is invalid in C99 [-Wimplicit-function-declaration]
                        shm_unlink(sid);
                        ^
/data/data/com.termux/files/home/uftrace/cmds/record.c:2147:35: error: use of undeclared
      identifier 'EFD_SEMAPHORE'
        ready = eventfd(0, EFD_CLOEXEC | EFD_SEMAPHORE);
```
https://android.googlesource.com/platform/bionic/+/master/docs/status.md

**Comment by honggyukim** [comment]
Thanks very much for doing this! I have some comments on this.

**1. Linux build doesn't actually use `libargp.a`**

It builds `libargp.a`, but doesn't actually use it when linking to `uftrace` binary. So I made some modification to do that.
```diff
diff --git a/Makefile b/Makefile
index 8dc0035..99d9cfb 100644
--- a/Makefile
+++ b/Makefile
@@ -131,7 +131,7 @@ include $(srcdir)/Makefile.include
 LIBMCOUNT_TARGETS := libmcount/libmcount.so libmcount/libmcount-fast.so
 LIBMCOUNT_TARGETS += libmcount/libmcount-single.so libmcount/libmcount-fast-single.so

-_TARGETS := uftrace libtraceevent/libtraceevent.a
+_TARGETS := uftrace libtraceevent/libtraceevent.a argp/libargp.a
 _TARGETS += $(LIBMCOUNT_TARGETS) libmcount/libmcount-nop.so
 _TARGETS += misc/demangler misc/symbols
 TARGETS  := $(patsubst %,$(objdir)/%,$(_TARGETS))
@@ -184,7 +184,7 @@ LIBMCOUNT_DEPS := $(COMMON_DEPS) $(srcdir)/libmcount/internal.h
 CFLAGS_$(objdir)/mcount.op = -pthread
 CFLAGS_$(objdir)/cmds/record.o = -DINSTALL_LIB_PATH='"$(libdir)"'
 CFLAGS_$(objdir)/cmds/live.o = -DINSTALL_LIB_PATH='"$(libdir)"'
-LDFLAGS_$(objdir)/uftrace = -L$(objdir)/libtraceevent -ltraceevent -ldl
+LDFLAGS_$(objdir)/uftrace = -L$(objdir)/libtraceevent -ltraceevent -L$(objdir)/argp -largp -ldl

 LIBMCOUNT_FAST_CFLAGS := -DDISABLE_MCOUNT_FILTER
 LIBMCOUNT_SINGLE_CFLAGS := -DSINGLE_THREAD
```
Then it tries to build it with `libargp.a`, but it still has a problem when linking as follows:
```
  LINK     uftrace
/home/honggyu/work/uftrace/argp/libargp.a(argp-parse.o): In function `argp_usage':
/home/honggyu/work/uftrace/argp/argp-parse.c:1282: multiple definition of `argp_usage'
/home/honggyu/work/uftrace/uftrace.o:/home/honggyu/work/uftrace/argp/argp.h:569: first defined here
/home/honggyu/work/uftrace/argp/libargp.a(argp-parse.o): In function `_option_is_short':
/home/honggyu/work/uftrace/argp/argp-parse.c:1288: multiple definition of `_option_is_short'
/home/honggyu/work/uftrace/uftrace.o:/home/honggyu/work/uftrace/argp/argp.h:575: first defined here
/home/honggyu/work/uftrace/argp/libargp.a(argp-parse.o): In function `_option_is_end':
/home/honggyu/work/uftrace/argp/argp-parse.c:1302: multiple definition of `_option_is_end'
/home/honggyu/work/uftrace/uftrace.o:/home/honggyu/work/uftrace/argp/argp.h:587: first defined here
collect2: error: ld returned 1 exit status
Makefile:276: recipe for target '/home/honggyu/work/uftrace/uftrace' failed
make: *** [/home/honggyu/work/uftrace/uftrace] Error 1
```

**2. Some compilation errors on termux**

It seems that the same problem was handled by termux community already. Please take a look at the following link.
- https://github.com/termux/termux-packages/tree/master/packages/uftrace

It includes some patches to handle (maybe) libc specific functions. For example, it also has `shm_open` library.
- https://github.com/termux/termux-packages/blob/master/packages/uftrace/cmds-record.c.patch

You can also have direct discussion with termux people just like they did previously in #851.

Thanks very much for your hard work!

**Comment by namhyung** [comment]
No I don't want to add another library dependency just for this.  Other than help and usage, is there any serious obstacle?  I also considered libsubcmd (well just copying the two files) but it seems just getopt(_long) works.

**Comment by gonapps** [comment]
@namhyung 
> Other than help and usage, is there any serious obstacle?

Not much, but I am worried about losing pretty formatted help and usage feature.
Also there are lots of code to rewrite, so it will take a lot of time.
My plan was initially adopt argp-standalone then support Android and replace it with getopt(_long) incrementally.
If you still don't agree with this, you can close this pull request.

**Comment by gonapps** [comment]
Compile succeeds and commands like this works in termux
```console
LD_LIBRARY_PATH=libmcount ./uftrace --auto-args --nest-libcall ls
```

**Comment by honggyukim** [comment]
Even if it cannot be merged right now. I think it worth to have a simple backup solution for Android support. I also think that including the entire argp code base may not be a good idea, but it can be customized and minimized for our own purpose with very limited features if possible.

I'm glad to hear that it works fine in termux now, but it cannot be compiled in normal Linux environment due to `shm_open` and `shm_unlink`.
```
$ make
  CC       cmds/record.o
In file included from /home/honggyu/work/uftrace/cmds/record.c:31:0:
/home/honggyu/work/uftrace/utils/posix_shm.h:20:19: error: static declaration of ‘shm_open’ follows non-static declaration
 static inline int shm_open(const char *file, int oflag, mode_t mode)
                   ^
In file included from /home/honggyu/work/uftrace/cmds/record.c:14:0:
/usr/include/x86_64-linux-gnu/sys/mman.h:144:12: note: previous declaration of ‘shm_open’ was here
 extern int shm_open (const char *__name, int __oflag, mode_t __mode);
            ^
In file included from /home/honggyu/work/uftrace/cmds/record.c:31:0:
/home/honggyu/work/uftrace/utils/posix_shm.h:34:19: error: static declaration of ‘shm_unlink’ follows non-static declaration
 static inline int shm_unlink(const char *file)
                   ^
In file included from /home/honggyu/work/uftrace/cmds/record.c:14:0:
/usr/include/x86_64-linux-gnu/sys/mman.h:147:12: note: previous declaration of ‘shm_unlink’ was here
 extern int shm_unlink (const char *__name);
            ^
Makefile:267: recipe for target '/home/honggyu/work/uftrace/cmds/record.o' failed
make: *** [/home/honggyu/work/uftrace/cmds/record.o] Error 1
```
At lease we need the following change.
```diff
diff --git a/utils/posix_shm.h b/utils/posix_shm.h
index 765e359..0c5f362 100644
--- a/utils/posix_shm.h
+++ b/utils/posix_shm.h
@@ -17,7 +17,7 @@
 #endif

 #ifndef HAVE_POSIX_SHM
-static inline int shm_open(const char *file, int oflag, mode_t mode)
+int shm_open(const char *file, int oflag, mode_t mode)
 {
        int ret;
        char* path;
@@ -31,7 +31,7 @@ static inline int shm_open(const char *file, int oflag, mode_t mode)
        return ret;
 }

-static inline int shm_unlink(const char *file)
+int shm_unlink(const char *file)
 {
        int ret;
        char* path;
```
@gonapps Thanks for your work!

**Comment by honggyukim** [comment]
@gonapps I actually don't have a clear idea about termux. Can you attach a recorded data image here so that we can better examine the termux environment.

In addition, I'm really curious about how termux people handled uftrace and made it work even without handling the option system.
- https://github.com/namhyung/uftrace/issues/851#issuecomment-530102407

As I mentioned, uftrace package is included in termux repository.
- https://github.com/termux/termux-packages/tree/master/packages/uftrace

**Comment by gonapps** [comment]
> In addition, I'm really curious about how termux people handled uftrace and made it work even without handling the option system.

Well they actually link argp-standalone package to uftrace.
https://github.com/termux/termux-packages/blob/master/packages/uftrace/build.sh

**Comment by namhyung** [comment]
NAK.  Please use getopt(_long) instead.

**Pull request closed without merging**
