### PR TITLE
misc: Add kali to install-deps.sh

### PR DESCRIPTION
**Pull request by kimdo331**
Since kali uses the same package install commands, it just simply adds kali to ubuntu case.

### CODE REVIEW

**Comment by honggyukim** [comment]
@kimdo331 Thanks very much for contributing uftrace!

Did you actually test this change on kali Linux machine?

**Comment by kimdo331** [comment]
Yes, i try to run edited shell and it worked.

This is my local environment.
```shell
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.4"
VERSION_ID="2019.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

**Comment by honggyukim** [comment]
Thanks for the confirmation. It looks okay then, but could you please change the commit message following the guideline?
- https://github.com/namhyung/uftrace/blob/master/CONTRIBUTING.md#signing-your-patch

In short, I would like to ask you to write a commit message as follows:
- Do not write more than 72 characters in a single line. Please break a line.
- Put a `Signed-off-by` line at the end. Please see other commit log with `git log`.
- Make sure that you're writing the commit with your real name rather than a nickname.

**Comment by kimdo331** [comment]
Is it fully changed to follow the guideline?

**Comment by honggyukim** [comment]
It looks fine again, but do not write commit message more than 72 characters in a single line. Please break a line when it goes over 72 characters.

**Comment by honggyukim** [comment]
@kimdo331 I recommend you to read other commit messages by running `git log`.

**Comment by kimdo331** [comment]
I don't know why this PR closed. Someone help me...

**Comment by namhyung** [comment]
Hmm.. I don't know.  Can you click "Reopen" button below?  It's disabled to me for some reason.

**Comment by honggyukim** [comment]
@kimdo331 This is the reason why you better send a PR with a different branch rather than `master`. Can you rebase the `master` and add your commit on top of it, then force push again?

If it doesn't work, then you better send it in a different PR.

**Comment by kimdo331** [comment]
I will send a new Pull Request. Thank you for advising me.

**Pull request closed without merging**
