### PR TITLE
utils: Add stacktrace and ASSERT, DASSERT

### PR DESCRIPTION
**Pull request by honggyukim**
This PR adds some debugging features for easier debugging.

The details are written in the commit message.

### CODE REVIEW

**Comment by honggyukim** [comment]
Simple output example of `stacktrace` is as follows.
```
$ uftrace record -F c --no-libcall t-abc
#0 /home/honggyu/usr/lib/libmcount.so(backtrace+0x9c) [0x7f40cee7862c]
#1 /home/honggyu/usr/lib/libmcount.so(+0x80b9) [0x7f40cee750b9]
#2 /home/honggyu/usr/lib/libmcount.so(+0x8614) [0x7f40cee75614]
#3 /home/honggyu/usr/lib/libmcount.so(+0x2712a) [0x7f40cee9412a]
#4 t-abc() [0x4009a3]
#5 t-abc() [0x400990]
#6 t-abc(main+0x3c) [0x400a18]
#7 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f40ceac3830]
#8 t-abc(_start+0x29) [0x400889]
```
```
$ uftrace replay
# DURATION     TID     FUNCTION
#0 uftrace(fstack_get+0x2f) [0x43f04f]
#1 uftrace() [0x4400de]
#2 uftrace() [0x441441]
#3 uftrace(command_replay+0xe0) [0x421b20]
#4 uftrace(main+0x523) [0x40a663]
#5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f427be12830]
#6 uftrace(_start+0x29) [0x40a789]

#0 uftrace(fstack_get+0x2f) [0x43f04f]
#1 uftrace() [0x4402d1]
#2 uftrace() [0x441441]
#3 uftrace(command_replay+0xe0) [0x421b20]
#4 uftrace(main+0x523) [0x40a663]
#5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f427be12830]
#6 uftrace(_start+0x29) [0x40a789]

#0 uftrace(fstack_get+0x2f) [0x43f04f]
#1 uftrace() [0x4400de]
#2 uftrace() [0x441441]
#3 uftrace(command_replay+0xe0) [0x421b20]
#4 uftrace(main+0x523) [0x40a663]
#5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f427be12830]
#6 uftrace(_start+0x29) [0x40a789]

#0 uftrace(fstack_get+0x2f) [0x43f04f]
#1 uftrace(fstack_entry+0x3d) [0x43f13d]
#2 uftrace(command_replay+0x3e0) [0x421e20]
#3 uftrace(main+0x523) [0x40a663]
#4 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f427be12830]
#5 uftrace(_start+0x29) [0x40a789]
    ...
```

**Comment by namhyung** [comment]
I'd like to see actual output from `CHECK` or `DCHECK`..

**Comment by honggyukim** [comment]
We may be able to print more helpful message with `CHECK` and `DCHECK`, but need to add these check routines many places. I'm thinking of adding `NULL` checks for arguments in almost every functions, but I don't know if you are okay with it.

I haven't uploaded this change, but the example output of `CHECK` is as follows.
```
$ uftrace report
/home/honggyu/work/uftrace/cmds/report.c:98: add_remaining_fstack: Assertion `!root' failed.
Stack trace:
  #0 uftrace() [0x40ffed]
  #1 uftrace() [0x410542]
  #2 uftrace() [0x410827]
  #3 uftrace(command_report+0x374) [0x4118d5]
  #4 uftrace(main+0x4f7) [0x40c7c5]
  #5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f1552007830]
  #6 uftrace(_start+0x29) [0x40a0d9]

Please report this uftrace internal bug to `https://github.com/namhyung/uftrace/issues'.
Aborted (core dumped)
```
In addition, I would like to know if there is a way to keep symbols of static functions. They don't actually show the function names in stack trace.

**Comment by honggyukim** [comment]
For example, these kind of check routines can be added.
```diff
diff --git a/cmds/report.c b/cmds/report.c
index 29f8bfa..cd57486 100644
--- a/cmds/report.c
+++ b/cmds/report.c
@@ -20,6 +20,7 @@ static LIST_HEAD(output_fields);

 static void print_field(struct uftrace_report_node *node, int space)
 {
+       CHECK(node);
        struct field_data fd = {
                .arg = node,
        };
@@ -43,6 +47,8 @@ static void insert_node(struct rb_root *root, struct uftrace_task_reader *task,
 static void find_insert_node(struct rb_root *root, struct uftrace_task_reader *task,
                             uint64_t timestamp, uint64_t addr, bool needs_srcline)
 {
+       CHECK(root);
+       CHECK(task);
        struct sym *sym;
        char *symname;
        struct debug_location *loc = NULL;
@@ -78,6 +87,9 @@ static void add_lost_fstack(struct rb_root *root, struct uftrace_task_reader *ta
 static void add_remaining_fstack(struct uftrace_data *handle,
                                 struct rb_root *root, struct opts *opts)
 {
+       CHECK(handle);
+       CHECK(root);
+       CHECK(opts);
        struct uftrace_task_reader *task;
        struct fstack *fstack;
        int i;
```
I hope to create a smart macro such as `CHECK_ARGS(handle, root, opts)` and it expands the arguments to `CHECK(handle); CHECK(root); CHECK(opts);` but I haven't found a good way to apply `CHECK` function to all the arguments yet.

`CHECK_ARGS` can make the code more concise but don't know if it's possible. Otherwise, we should add all check routines one by one.

**Comment by honggyukim** [comment]
@namhyung I've just updated this PR. You can test it by adding some `CHECK` or `DCHECK` routines anywhere, but make it fail to show the message.

**Comment by honggyukim** [comment]
> I hope to create a smart macro such as CHECK_ARGS(handle, root, opts) and it expands the arguments to CHECK(handle); CHECK(root); CHECK(opts); but I haven't found a good way to apply CHECK function to all the arguments yet.

I found a way to implement this from external resource so brought the code and implemented `CHECK_ALL` and `DCHECK_ALL`. I've added `DCHECK_ALL` for most of function arguments to detect some segfaults due to null pointer dereference at an early stage.

@namhyung Please let me know how you think about this.

**Comment by namhyung** [comment]
Sounds good.

**Comment by honggyukim** [comment]
Sorry, the update is very late. The changes are as follows.
- use libunwind version `stacktrace` when `DEBUG=1`.
- replace `CHECK`, `DCHECK` to `ASSERT`, `DASSERT`
- replace all the existing `assert` to `ASSERT`

I introduced libunwind version `stacktrace` only for debug build not to add an additional dependency. The difference between two different `stacktrace` is as follows.

The libunwind version in debug mode is as follows.
```
      Stack trace:
        #1  0x00000045390a fstack_update_stack_count + 0x2c
        #2  0x000000454081 __fstack_consume + 0x48f
        #3  0x000000454b62 __read_rstack + 0x74e
        #4  0x000000454bbb read_rstack + 0x28
        #5  0x000000417386 command_replay + 0x28e
        #6  0x000000407bf9 main + 0x4c3
        #7  0x7f6d119f9840 __libc_start_main + 0xf0
        #8  0x0000004054e9 _start + 0x29
        #9  0x000000000000  + 0x29
```
The exiting backtrace in release mode doesn't show static function names.
```
      Stack trace:
        #1  uftrace() [0x442277]
        #2  uftrace() [0x443ced]
        #3  uftrace(command_replay+0xe8) [0x415f28]
        #4  uftrace(main+0x544) [0x40ae14]
        #5  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f52982e0840]
        #6  uftrace(_start+0x29) [0x40af49]
```

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
