### PR TITLE
mcount: Generate .dbg file for library with debug section

### PR DESCRIPTION
**Pull request by ekyooo**
It generates .dbg file for every library with debug information
linked to the main executable when recording with --srcline option.

Fixed: #1138

Signed-off-by: Eunseon Lee <esintospace@gmail.com>

### CODE REVIEW

**Comment by ekyooo** [comment]
Now I'm not sure if it's right direction. 
To get your opinion, I'll share what made the issue in next comment.

This is test changed result of it.

```
$ uftrace record --srcline test/t-lib

$ ls uftrace.data/*.dbg
uftrace.data/libabc_test_lib.so.dbg  uftrace.data/t-lib.dbg

$ ./uftrace report --srcline
  Total time   Self time       Calls  Function [Source]
  ==========  ==========  ==========  ====================
   13.810 us    1.424 us           3  lib_a
    7.227 us    0.667 us           2  lib_b [/home/bingbong/soft/uftrace/tests/s-lib.c:15]
    6.315 us    0.351 us           1  main [/home/bingbong/soft/uftrace/tests/s-libmain.c:16]
    5.964 us    0.772 us           1  foo [/home/bingbong/soft/uftrace/tests/s-libmain.c:11]
    4.825 us    3.101 us           2  lib_c [/home/bingbong/soft/uftrace/tests/s-lib.c:20]
```

**Comment by ekyooo** [comment]
The cause was map->mod of libabc_test_lib was NULL in the function below.
This patch is to load module for all linked library not just main executable.
Please give any opinion.
Thank you.

dwarf.c
```
1142 void prepare_debug_info(struct symtabs *symtabs,
...
1170         for_each_map(symtabs, map) {
1171                 struct symtab *stab = &map->mod->symtab;
1172                 struct debug_info *dinfo = &map->mod->dinfo;
1173
1174                 if (map->mod == NULL)
1175                         continue;  // --> go this case for libabc_test_lib
1176
1177                 setup_debug_info(map->libname, dinfo, map->start, force);  // --> so not setup debug info for libabc_test_lib
```

Also please let me know if there any test cases related to this modification.
```
$ ./runtest.py dwarf
Start 4 tests with 4 worker
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
201 arg_dwarf1          : OK OK OK OK OK SK SK SK SK SK
202 arg_dwarf2          : OK OK OK OK OK SK SK SK SK SK
203 arg_dwarf3          : OK OK NG NG NG SK SK SK SK SK
204 arg_dwarf4          : OK OK OK OK OK SK SK SK SK SK
```

**Comment by ekyooo** [comment]
@namhyung,@honggyukim 
This PR is updated.
(I found that you are not in participant. so I share it.) 
Thank you.

**Comment by namhyung** [comment]
To be clear, it affects only when `--srcline` option is given.  If one of `-A`, `-R` or `-a` is used they'd generate debug info files without this change, right?

**Comment by ekyooo** [comment]
> To be clear, it affects only when `--srcline` option is given. If one of `-A`, `-R` or `-a` is used they'd generate debug info files without this change, right?

Yes, I intended it. It can be run with --srcline option because the function(mcount_filter_init) checks if srcline is applied before run it.
In case that one of `-A`, `-R` or `-a` is used, function below is already used if those options are filters.
(if mcount_filter_init function with DISABLE_MCOUNT_FILTER disabled is used with those three options.) It it right?
```
load_module_symtabs(&symtabs);
```

**Comment by ekyooo** [comment]
Yes. I checked that it affects only when --srcline option is given. If one of -A, -R or -a is used they'd generate debug info files without this change because called mcount_filter_init is different.

**Comment by namhyung** [comment]
Can you please update the test number?

**Comment by ekyooo** [comment]
test number is updated to 246. thank you.

**Pull request merged**
