### PR TITLE
uftrace: Update TODO list

### PR DESCRIPTION
**Pull request by Taeung**
The commit d79e36c3 ("arch/x86: Support dynamic tracing for clang xray")
support clang xray, so remove it on TODO list

### CODE REVIEW

**Comment by Taeung** [comment]
OKey, I also remove them.

> - gcc5 -mnop-mcount support
> - dynamic instrumentation

But `-mrecord-mcount` option isn't supported yet, right ?

**Comment by Taeung** [comment]
I sent PRv2 !

**Comment by namhyung** [comment]
Yes but I think it's not needed, so let's get rid of it.

**Comment by Taeung** [comment]
Okey, I'll remove the line `- gcc5 -mrecord-mcount support` on TODO list, too.

**Comment by Taeung** [comment]
@namhyung , I sent v3 !

**Pull request merged**
