### PR TITLE
scripts: Add uftrace_event handling in dump.{py,lua} and fix dump.lua

### PR DESCRIPTION
**Pull request by honggyukim**
This PR adds uftrace_event handling in dump.py and dump.lua as follows.

      $ gcc -pg -o t-sleep tests/s-sleep.c
      $ uftrace record --no-libcall t-sleep
      $ uftrace script -S scripts/dump.py
      uftrace_begin(ctx)
        record  : False
        version : v0.11-63-g6eba47 ( x86_64 dwarf python luajit tui perf sched dynamic )
        cmds    :

      9826991.615165883  17706: [entry] main(400850) depth: 0
      9826991.615166494  17706: [entry] foo(40082a) depth: 1
      9826991.615166805  17706: [entry] mem_alloc(4007db) depth: 2
      9826991.615167952  17706: [exit ] mem_alloc(4007db) depth: 2
      9826991.615169119  17706: [entry] bar(400810) depth: 2
      9826991.615185663  17706: [event] linux:sched-out(30d42)
      9826991.617290083  17706: [event] linux:sched-in(30d41)
      9826991.617296237  17706: [exit ] bar(400810) depth: 2
      9826991.617298178  17706: [entry] mem_free(4007f4) depth: 2
      9826991.617301510  17706: [exit ] mem_free(4007f4) depth: 2
      9826991.617301821  17706: [exit ] foo(40082a) depth: 1
      9826991.617302177  17706: [exit ] main(400850) depth: 0

      uftrace_end()

It also fixes a timestamp print error in `dump.lua` script.
In dump.lua script, timestamp print logic is incorrect so the timestamp
output looks very different from dump.py output as follows.

      $ uftrace script -S scripts/dump.py | grep event
      9826512.975114342  17094: [event] linux:sched-out(30d42)
      9826512.977219263  17094: [event] linux:sched-in(30d41)

      $ uftrace script -S scripts/dump.lua | grep event
      446122998880.7426  17094: [event] linux:sched-out(30d42)
      446122998975.19834  17094: [event] linux:sched-in(30d41)

This PR also fixes the timestamp logic and the output now looks same as
dump.py output as follows.

      $ uftrace script -S scripts/dump.lua | grep event
      9826512.975114342  17094: [event] linux:sched-out(30d42)
      9826512.977219264  17094: [event] linux:sched-in(30d41)

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Review by namhyung — COMMENTED** [review]
@binkoni Could you please take a look?

**Comment by binkoni** [comment]
Hi @honggyukim, @namhyung, I looked at the code and it seems to be OK :)

**Comment by namhyung** [comment]
Thanks for checking it!

**Comment by honggyukim** [comment]
@binkoni It's good to see you again here. @namhyung I've just rebased it again.

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
