### PR TITLE
New release: v0.14

### PR DESCRIPTION
**Pull request by namhyung**
It's time for a new release.  Please test and report any issues!

In this development cycle, we've seen many interesting changes including:
 * Python language support
 * Runtime option changes with agent
 * Android build support

And of course, a lot more fixes and improvements are there as well.  Thanks for all the contributors.

### CODE REVIEW

**Comment by honggyukim** [comment]
Hi, thanks for preparing the release.

I've ran the tests and got the following result.
```
$ ./runtest.py
$ cat failed-tests.txt.full 
Compiler                  gcc                                           clang                                       
Test case                 pg             finstrument-fu fpatchable-fun  pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os
028 replay_backtrace    : NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG  NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG
124 exception           : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NG NG NG NG NG OK OK OK OK OK
165 graph_sched         : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK OK OK OK OK OK NG OK
182 thread_exit         : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK OK OK SG OK OK OK OK
185 exception2          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NG NG NG NG NG OK OK OK OK OK
186 exception3          : OK OK OK OK OK OK OK OK OK OK NG NG NG NG NG  OK OK OK OK OK NG NG NG NG NG NG NG NG NG NG
196 chrome_taskname     : OK OK NG OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK
203 arg_dwarf3          : OK OK NG NG NG SK SK SK SK SK OK OK NG NG NG  OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK
204 arg_dwarf4          : OK OK NG NG OK SK SK SK SK SK OK OK NG NG OK  OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK
212 noplt_libcall       : NG NG NG NG NG OK OK OK OK OK OK OK OK OK OK  NG NG NG NG NG NG NG NG NG NG OK OK OK OK OK
251 exception4          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NZ NZ NZ NZ NZ OK OK OK OK OK
255 arg_dwarf6          : OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK  NG NG NG NG NG SK SK SK SK SK NG NG NG NG NG
281 agent_trace_toggle  : NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG  NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG
```
It looks 281 is due to timing issue, but we have to check 028 replay_backtrace test.
```diff
$ ./runtest.py -dp -O0 -c gcc 028
Start 1 tests without worker pool

Compiler                  gc
Test case                 pg
------------------------: O0
t028_replay_backtrace: diff result of gcc -pg -O0
--- expect      2023-06-03 14:42:02.775607669 +0900
+++ result      2023-06-03 14:42:02.775607669 +0900
@@ -1 +1,7 @@
+ __monstartup();
+ __cxa_atexit();
+ main() {
+   alloc1() {
+     alloc2() {
+       alloc3() {
  /* [ 0] main */
@@ -4,6 +10,21 @@
  /* [ 3] alloc3 */
- alloc4() {
-   alloc5() {
-     malloc();
-   } /* alloc5 */
- } /* alloc4 */
+         alloc4() {
+           alloc5() {
+             malloc();
+           } /* alloc5 */
+         } /* alloc4 */
+       } /* alloc3 */
+     } /* alloc2 */
+   } /* alloc1 */
+   free1() {
+     free2() {
+       free3() {
+         free4() {
+           free5() {
+             free();
+           } /* free5 */
+         } /* free4 */
+       } /* free3 */
+     } /* free2 */
+   } /* free1 */
+ } /* main */

028 replay_backtrace    : NG
```
The issue is filed at #1723

**Comment by namhyung** [comment]
Thanks for the report.  I've just loaded a fix for the backtrace problem.  Also I don't see the problem in the agent tests.

**Comment by honggyukim** [comment]
After applying the fix, 028 is fine now. The current failed tests are as follows.
```
$ cat failed-tests.txt
Compiler                  gcc                                           clang                                       
Test case                 pg             finstrument-fu fpatchable-fun  pg             finstrument-fu fpatchable-fun
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os  O0 O1 O2 O3 Os O0 O1 O2 O3 Os O0 O1 O2 O3 Os
124 exception           : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NG NG NG NG NG OK OK OK OK OK
150 recv_event          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK NZ OK OK OK OK OK OK
165 graph_sched         : OK OK OK OK OK OK OK OK OK OK NG OK OK OK OK  OK OK OK OK OK OK OK OK OK OK OK NG OK OK OK
167 recv_sched          : OK OK NZ OK OK OK OK OK OK OK OK OK OK OK NZ  OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK
182 thread_exit         : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK OK OK OK OK OK SG OK OK OK OK
185 exception2          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NG NG NG NG NG OK OK OK OK OK
186 exception3          : OK OK OK OK OK OK OK OK OK OK NG NG NG NG NG  OK OK OK OK OK NG NG NG NG NG NG NG NG NG NG
203 arg_dwarf3          : OK OK NG NG NG SK SK SK SK SK OK OK NG NG NG  OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK
204 arg_dwarf4          : OK OK NG NG OK SK SK SK SK SK OK OK NG NG OK  OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK
212 noplt_libcall       : NG NG NG NG NG OK OK OK OK OK OK OK OK OK OK  NG NG NG NG NG NG NG NG NG NG OK OK OK OK OK
226 default_opts        : NG OK OK OK OK OK OK NG OK OK OK OK NG OK NG  OK OK OK OK OK OK OK OK OK OK OK OK NG NG OK
251 exception4          : OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK  OK OK OK OK OK NZ NZ NZ NZ NZ OK OK OK OK OK
255 arg_dwarf6          : OK OK OK OK OK SK SK SK SK SK OK OK OK OK OK  NG NG NG NG NG SK SK SK SK SK NG NG NG NG NG
283 agent_time          : NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG  NG NG NG NG NG NG NG NG NG NG NG NG NG NG NG
284 agent_filter        : OK OK OK OK OK OK OK OK OK OK OK OK NZ OK OK  OK OK OK OK OK OK OK OK OK OK OK OK OK OK OK
```
It shows another agent test failures but it might be related when multiple agents running together so I think it can be ignored.

It also shows a bit more random failures but they don't have to be fixed all together now.

**Comment by honggyukim** [comment]
The `SG` in 182 thread_exit was already reported at #1364.
```
$ ./runtest.py -O0 -e 182
Start 1 tests without worker pool

Compiler                  gc  cl
Test case                 fp  fp
------------------------: O0  O0
182 thread_exit         : OK  SG
```

**Comment by honggyukim** [comment]
We better run minimal 32-bit build test.

**Comment by honggyukim** [comment]
And it might be better to ask @bernhardkaindl or @thepaul for basic build check for packaing before making a release.

There could be some issues because we now started to support python tracing from this release.

**Comment by honggyukim** [comment]
> We better run minimal 32-bit build test.

Build test is fine but unittest with asan complains with some memory leak reports.

**Comment by honggyukim** [comment]
I just confirmed that android build is fine without a problem.
```
$ export NDK=$HOME/tools/android-ndk-r25c
$ export CC=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
$ export LD=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld

$ ./configure --arch=aarch64 --cross-compile=aarch64-linux-gnu- --without-libpython --without-libstdc++
      ...
$ make
      ...
$ file uftrace
uftrace: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, with debug_info, not stripped
```

**Comment by honggyukim** [comment]
In addition, we might be better to clarify if python2 tracing is supported? I haven't tested it.

**Comment by namhyung** [comment]
I've tested it and it works at least on my machine.

**Comment by MichelleJin12** [comment]
I have the same problem as https://github.com/namhyung/uftrace/pull/1725#issuecomment-1577978923.

```
(venv) vagrant@vagrant:~/uftrace/tests$ ./runtest.py -P 004
Start 1 tests without worker pool

Python test case          Result
--------------------------------
004 filter_FN           : SG

(venv) vagrant@vagrant:~/uftrace/tests$ ./runtest.py -P
Start 12 tests with 2 worker

Python test case          Result
--------------------------------
001 basic               : OK
002 filter_F            : OK
003 filter_N            : OK
004 filter_FN           : SG
005 srcline             : OK
006 filter_time         : OK
007 filter_depth        : OK
008 file_var            : OK
009 libcall_single      : OK
010 libcall_none        : OK
011 libcall_nested      : OK
012 os_exit             : OK
```

However, replace # with ''' comment like below, and it passes.

```
'''Symbol and debug files are finally written at uftrace_trace_python_finish()
when program exits, but os._exit() terminates the program immediately so there
is no chance to write symbol and debug files at the destructor.
The os._exit() is hooked here to prevent this problem.'''
```

**Comment by namhyung** [comment]
> I have the same problem as https://github.com/namhyung/uftrace/pull/1725#issuecomment-1577978923.

Thanks for testing.  But it's not reasonable that deleting the comment changes the result.  Are you running the latest version?

**Comment by MichelleJin12** [comment]
Yes, I run the latest version of uftrace.

You're right, it's not the comment problem. I tested using Python installed on the system, not venv, it passed regardless of the comment.

**Comment by namhyung** [comment]
**Note for packagers**: the default library installation directory was changed to have a separate "uftrace" directory.  I think it's better to have it to carry different flavors of libmcount and now python tracing module too.  While uftrace should be able to find the installed library, you may want to add it to ld.so.conf or something.

**Comment by namhyung** [comment]
@MichelleJin12 thanks for your reply.  I've realized that I forgot to push the related changes.  Could you please test it again with the current master?

Also I've updated some documents, please correct my English. :)

**Comment by MichelleJin12** [comment]
Sure, 
It passed all Python test cases with the current master, and I checked the updated docs, LGTM.

**Comment by namhyung** [comment]
@MichelleJin12 thanks a lot!

**Pull request merged**
