### PR TITLE
Support i386 

### PR DESCRIPTION
**Pull request by ParkHanbum**
this "PR" is splitted part from "support-i386".
this "PR" contain support i386 for uftrace.

first commit:
```
arch/i386: add basic support for i386 architecture

support fentry, mcount instrumentation feature for i386.
not support dynamic trace and xray yet.

add "mcount_arch_child_idx" function for i386 architecture.
in i386, child_idx is a multiple of 8 unlike other architecture.
therefore, child_idx must be divided by 8 to match the symbol order.
```
second commit:
```
arch/i386: support dynamic tracing.

support dynamic trace feature for i386.
In case of gcc which is not patched because of old version,
it may not create 5 byte nop.
however, when meet case like that,
dynamic trace does not proceed anymore.
so, there is no need to worry.

and in i386, it is not possible to refer to instruction pointer register.
therefore changed a trampoline to following:
=====================================
call 0x5
pop eax
jmp dword ptr [eax + 4]
=====================================
first call instruction point next line of assembly "pop eax".
it is work well.
```

### CODE REVIEW

**Comment by ParkHanbum** [comment]
I think what you say and what I mention is the same. 
because "call 0x5" is assembly, not include its own length that increase when translation.

**Comment by namhyung** [comment]
Yes I meant it.  Could you confirm that assembly `call 0x5` is translated to `e9 00 00 00 00`?

**Comment by ParkHanbum** [comment]
ok, just wait a minute.

**Comment by ParkHanbum** [comment]
(gdb) disas main
Dump of assembler code for function main:
=> 0x08048593 <+0>:     nopl   0x0(%eax,%eax,1)
   0x08048598 <+5>:     lea    0x4(%esp),%ecx
   0x0804859c <+9>:     and    $0xfffffff0,%esp
   0x0804859f <+12>:    pushl  -0x4(%ecx)
   0x080485a2 <+15>:    push   %ebp
   0x080485a3 <+16>:    mov    %esp,%ebp
   0x080485a5 <+18>:    push   %ecx
   0x080485a6 <+19>:    sub    $0x14,%esp
   0x080485a9 <+22>:    mov    %ecx,%eax
   0x080485ab <+24>:    movl   $0x0,-0xc(%ebp)
   0x080485b2 <+31>:    cmpl   $0x1,(%eax)
   0x080485b5 <+34>:    jle    0x80485ce <main+59>
   0x080485b7 <+36>:    mov    0x4(%eax),%eax
   0x080485ba <+39>:    add    $0x4,%eax
   0x080485bd <+42>:    mov    (%eax),%eax
   0x080485bf <+44>:    sub    $0xc,%esp
   0x080485c2 <+47>:    push   %eax
   0x080485c3 <+48>:    call   0x80483e0 <atoi@plt>
   0x080485c8 <+53>:    add    $0x10,%esp
   0x080485cb <+56>:    mov    %eax,-0xc(%ebp)
   0x080485ce <+59>:    call   0x8048536 <a>
   0x080485d3 <+64>:    add    %eax,-0xc(%ebp)
   0x080485d6 <+67>:    cmpl   $0x0,-0xc(%ebp)
   0x080485da <+71>:    sete   %al
   0x080485dd <+74>:    movzbl %al,%eax
   0x080485e0 <+77>:    mov    -0x4(%ebp),%ecx
   0x080485e3 <+80>:    leave
   0x080485e4 <+81>:    lea    -0x4(%ecx),%esp
   0x080485e7 <+84>:    ret
End of assembler dump.
(gdb) disas 0x8048536
Dump of assembler code for function a:
   0x08048536 <+0>:     call   0x8048ff0
   0x0804853b <+5>:     push   %ebp
   0x0804853c <+6>:     mov    %esp,%ebp
   0x0804853e <+8>:     sub    $0x8,%esp
   0x08048541 <+11>:    call   0x804854b <b>
   0x08048546 <+16>:    sub    $0x1,%eax
   0x08048549 <+19>:    leave
   0x0804854a <+20>:    ret
End of assembler dump.
(gdb) b *0x8048536
Breakpoint 3 at 0x8048536
(gdb) c
Continuing.

Breakpoint 3, 0x08048536 in a ()
(gdb) si
0x08048ff0 in ?? ()
(gdb) x/3i $eip
=> 0x8048ff0:   call   0x8048ff5
   0x8048ff5:   pop    %eax
   0x8048ff6:   jmp    *0x4(%eax)
(gdb) si
0x08048ff5 in ?? ()
(gdb) si
0x08048ff6 in ?? ()
(gdb) si
__fentry__ () at /home/m/uftrace/arch/i386/fentry.S:4
warning: Source file is more recent than executable.
4               sub $32, %esp
(gdb)

**Comment by namhyung** [comment]
I can see it uses a target address so `call 0x5` is fine, thanks!

And then, could you please combine the first and second patch?

**Comment by ParkHanbum** [comment]
@namhyung sure!

**Comment by namhyung** [comment]
Exactly!

**Comment by ParkHanbum** [comment]
@namhyung ok, it seems to be done.

**Comment by namhyung** [comment]
Could you please rebase it onto the current master?  Also it'd be nice if you could move the test-update commits here.

**Comment by ParkHanbum** [comment]
@namhyung sure, I'd like it.

**Pull request closed without merging**
