### PR TITLE
test: Fixed warning on tests/s-dwarf2

### PR DESCRIPTION
**Pull request by kangtegong**
This commit amends test warning referred on issue #1250

Signed-off-by: Kang Minchul <tegongkang@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
The change is good but can you modify your commit title from "test:Fixed Warning on test/s-dwarf2" to "test: Fixed Warning on test/s-dwarf2"? We give a single space right after "test:".

**Comment by kangtegong** [comment]
Ok, I just amended the commit message!

**Review by namhyung — APPROVED** [review]
LGTM

**Comment by namhyung** [comment]
Idealy you can add the actual warning message you fixed to the commit message.  But as the issue 1250 already mentioned, you can just add 'Fixed: #1250' line.  In general, it'd be good to see other commit message structures.

Anyway, thanks for your contribution!

**Comment by kangtegong** [comment]
> Idealy you can add the actual warning message you fixed to the commit message. But as the issue 1250 already mentioned, you can just add 'Fixed: #1250' line. In general, it'd be good to see other commit message structures.
> 
> Anyway, thanks for your contribution!

Oh ok, Thanks for your advice :)

**Comment by honggyukim** [comment]
@kangtegong So the ideal commit message looks as follows
```
tests: Fix a compiler warning in tests/s-dwarf2.cpp

This patch fixes the following compiler warning in tests/s-dwarf2.cpp.

  $ g++ tests/s-dwarf2.cpp
  tests/s-dwarf2.cpp: In function ‘int main()’:
  tests/s-dwarf2.cpp:30:17: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     30 |  A(E, FOO, BAR, "debug info test");
        |                 ^~~~~~~~~~~~~~~~~

  $ clang++ tests/s-dwarf2.cpp
  tests/s-dwarf2.cpp:30:17: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
          A(E, FOO, BAR, "debug info test");
                         ^
  1 warning generated

Fixed: #1250

Signed-off-by: Minchul Kang <tegongkang@gmail.com>
```
The last part `Fixed: #1250` is important because if this patch is merged into master, then github automatically closes the issue #1250. Please read more commit messages by running `git log`.

**Comment by kangtegong** [comment]
Thank you @honggyukim :) (I just amended the commit)

**Pull request merged**
