### PR TITLE
several minor fix. 

### PR DESCRIPTION
**Pull request by ParkHanbum**
the 3rd commit contain the patch that support to next feature. 
if you think it never required others, let me know. 
I'll push it next, not this.

### CODE REVIEW

**Comment by namhyung** [comment]
I think it's better to include the first patch when it's really used.  Also I don't see why the second patch is needed.  For the third patch, I think it'd be more natural to see filename before the error string.

Finally you missed to add your Sign-off in the commit logs. :)

**Comment by namhyung** [comment]
When did you see the HUP and what do you want to do?  The patch should describe it instead of just printing debug messages.

**Comment by ParkHanbum** [comment]
@namhyung That's all I want to know. At least it allows me to know what is happening and to find the cause of the incident. it is not about "Handling POLLHUP and POLLERR " but it is aobut "let us know exactly what we've met case."

**Comment by namhyung** [comment]
I don't want to add the current commit since it has no more information.  Please add some logic if you find out the cause of the POLLHUP later.

**Comment by ParkHanbum** [comment]
@namhyung OK, I respect you. but let me ask you just one question. if user met POLLHUP or POLLERR for unspecificied reason, How could user report that issue?

**Comment by namhyung** [comment]
@ParkHanbum sorry for late.  well I don't know.. if an user meet such a case it's hard to know it's because of the failed poll() or something.  Let's leave it now and think about when a report comes up.

**Pull request closed without merging**
