### PR TITLE
configure: fix error when building out of source

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by honggyukim** [comment]
Hi @licy183, thanks for the fix!

The change looks good, but could you update your email properly in the commit? It currently looks as `45286352+licy183@users.noreply.github.com` and I don't think this is your proper email address.

You can see that from https://github.com/namhyung/uftrace/pull/1737.patch.
```
From ae7ed14fc023d8c6ead8e2b4f88dd443a25a102a Mon Sep 17 00:00:00 2001
From: Uchiha Kakashi <45286352+licy183@users.noreply.github.com>
Date: Fri, 23 Jun 2023 01:26:42 +0800
Subject: [PATCH] configure: fix error when building out of source

Signed-off-by: Uchiha Kakashi <45286352+licy183@users.noreply.github.com>
```

**Comment by namhyung** [comment]
Could you please be more specific to which errors you actually saw?  You can put the command line and the error messages (with some indentation) in the commit log.  Thanks!

**Comment by licy183** [comment]
I have rewritten the commit log with the error message, and I've changed the my email in the commit log. Please review it, thanks!

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
