### PR TITLE
doc: Translate report.md - name, synopsis in Korean

### PR DESCRIPTION
**Pull request by rrabit42**
Hi, this is my first PR, and I am so nervous!
I'm in charge of translation of uftrace-report.md in Korean.

I'm wondering if I can translate man page like this.
So, at first, I translated 'name' and 'synopsis' parts. In here, I paraphrase the 'synopsis' to '사용법' not '개요' which is a dictionary meaning of a synopsis. And I try to translate a 'statistics' better, but I can't find a proper word so I just translate it to '통계자료'.

I want to know your opinions about my translations, and if it is fine, I'll continue the translation like this.

Thank you:)

### CODE REVIEW

**Comment by namhyung** [comment]
Thanks for the contribution, the translation looks good to me!

**Comment by gy741** [comment]
The world could always use more heroes.

commit shall include "Signed-off-by" and Include subject word in message header.

Ref:
https://github.com/namhyung/uftrace/blob/master/CONTRIBUTING.md

**Comment by rrabit42** [comment]
Thank you for your advices. I will include them after commits! Thanks :)

**Comment by honggyukim** [comment]
Thanks @rrabit42. Please let us know if you have any problems. You can also speak to us in Korean chat room in https://gitter.im/uftrace/ko.

**Pull request closed without merging**
