### PR TITLE
some fix for uftrace

### PR DESCRIPTION
**Pull request by ParkHanbum**
this "PR" is splitted part from "support-i386".
two fix for uftrace.

first commit:
```
trigger: do not use memcpy() for copying trigger

if we use memcpy to copy the &iter->trigger,
depending on the size of the uftrace_trigger *tr
we will ride optimization path to use SSE inside memcpy.
it will change status of SIMD register like mmx.
therefore we lose original value of register.
so, we decide not to use memcpy.
```

second commit:
```
mcount: add mcount_arch_child_idx()

The value of child idx may be different for each architecture.
For this reason, we added the part that calculates child_idx
to be implemented by each architecture.
```

### CODE REVIEW

**Comment by ParkHanbum** [comment]
I can not believe it. I'm sososososososo stupid!
Sorry about that.

**Comment by namhyung** [comment]
Do not blame yourself, everyone makes a mistake. :)

**Comment by namhyung** [comment]
Sign off please!

**Comment by ParkHanbum** [comment]
@namhyung OK. it is done!

**Pull request merged**
