### PR TITLE
Fix test failure in 207 dump_graphviz

### LINKED ISSUE #1568: test failure in 207 dump_graphviz
```diff
$ ./runtest.py -vpd -O0 -c gcc 207
Start 1 tests without worker pool
Compiler                  gc
Test case                 pg
------------------------: O0
    ...
t207_dump_graphviz: diff result of -pg -O0
--- expect      2022-09-04 08:49:53.364523026 +0100
+++ result      2022-09-04 08:49:53.364523026 +0100
@@ -2,3 +2,3 @@
 digraph "t-abc" {
-"main" [xlabel = "1"]
+"t-abc" -> "main" [xlabel = "1"]
 "main" -> "a" [xlabel = "1"]

207 dump_graphviz       : NG
```

### PR DESCRIPTION
**Pull request by ghojeong**
Closes #1568

I fixed test failure by changing expected out put at dump_graphviz.py

### CODE REVIEW

**Comment by honggyukim** [comment]
The change is good, but please read other commit messages and follow the same format.

**Comment by ghojeong** [comment]
I tried to follow the format of 4d438c13ac95e32bca0c25be28ef43b92f1d4e3b .
Please give me feedback, if the commit message is still inappropriate.

**Comment by honggyukim** [comment]
Thanks. This change is a simple fix, but don't have to include a long commit message. But it's okay to leave it as is.

**Review by honggyukim — APPROVED** [review]
LGTM

**Pull request merged**
