### PR TITLE
misc: Change debug.sh using custom command & argv

### PR DESCRIPTION
**Pull request by DanielTimLee**
This commit allows using custom command & argv with debug.sh

Example:
    sh misc/debug.sh tests/t-fibonacci 5

If no arguments are passed to debug.sh, it defaults to tests/t-abc.

Fixed: #511

Signed-off-by: Daniel T. Lee <danieltimlee@gmail.com>

### CODE REVIEW

**Comment by DanielTimLee** [comment]
#511

**Comment by namhyung** [comment]
Do you have something to add?

**Comment by DanielTimLee** [comment]
Nope. All done!

**Comment by namhyung** [comment]
Actually `misc/debug.sh` doesn't aim a perfect solution and expects some changes during debugging.  In other words, it's a kind of example how to debug.  But it's good to make it flexible as much as possible.

**Comment by DanielTimLee** [comment]
Thank you for your insight!

**Pull request merged**
