### PR TITLE
misc: Add Dockerfiles for arch, centos, ubuntu

### LINKED ISSUE #886: Support docker images
I'm thinking of adding Dockerfiles to this project.
If I add Dockerfiles for various distros such as ubuntu, arch, centos, apine..
It would be easier to test uftrace in other environments.

According to [this post](https://twitter.com/brendangregg/status/508094166769737728?lang=en) it seems possible to trace kernel functions inside containers.

### PR DESCRIPTION
**Pull request by gonapps**
Using Dockerfiles, you can test uftrace on multiple distros easily.
docker build -t <tagname> .
This fixes #886

Signed-off-by: Byeonggon Lee <gonny952@gmail.com>

### CODE REVIEW

**Comment by gy741** [comment]
Hello,

a just simple comment.

uftrace has a dependency installation script.

`misc/install-deps.sh`
> https://github.com/namhyung/uftrace/blob/master/misc/install-deps.sh

**Comment by gonapps** [comment]
@gy741 I didn't use install-deps.sh because this issue #883 is not fixed yet. I could make pull request myself to that issue, but I'm waiting for @henrychoi7

**Comment by namhyung** [comment]
You can use the script even if it's not ready yet since uftrace can be built without any dependent libraries.  Once the archlinux support code is added, it'll automatically use them later.

**Comment by gonapps** [comment]
@namhyung Now I used misc/install-deps.sh in Dockerfiles. It looks like there is nothing more to do.

**Comment by namhyung** [comment]
I don't want to have 2 commits for this.  Could you please squash them into one?

**Comment by gonapps** [comment]
I squashed just now

**Pull request merged**
