### PR TITLE
doc: Add uftrace live demo in GIF format

### PR DESCRIPTION
**Pull request by honggyukim**
It'd be better add uftrace live mode in GIF format to give better
understanding for general users.

The character size of terminal in GIF file is 80 x 29.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
Force updated again.

ChangeLog:
- move GIF image into doc directory
- resize the image from 75% to 80%

Please take a look at it. Thanks!

**Comment by namhyung** [comment]
LGTM!

**Comment by namhyung** [comment]
Hmm.. is the resizing necessary?

**Comment by honggyukim** [comment]
Force updated again.

ChangeLog:
- resize the image to original size again.

Thanks!

**Pull request merged**
