### PR TITLE
chrome: Add task names for each process

### PR DESCRIPTION
**Pull request by honggyukim**
It was missing to add base process name at the beginning of header so
this patch adds it.

  {"traceEvents":[
  {"ts":0,"ph":"M","pid":149779,"name":"process_name","args":{"name":"[149779] gcc-5"}},
  {"ts":0,"ph":"M","pid":149779,"name":"thread_name","args":{"name":"[149779] gcc-5"}},
  {"ts":0,"ph":"M","pid":149790,"name":"process_name","args":{"name":"[149790] cc1"}},
  {"ts":0,"ph":"M","pid":149790,"name":"thread_name","args":{"name":"[149790] cc1"}},
  {"ts":0,"ph":"M","pid":149791,"name":"process_name","args":{"name":"[149791] x86_64-linux-gn"}},
  {"ts":0,"ph":"M","pid":149791,"name":"thread_name","args":{"name":"[149791] x86_64-linux-gn"}},
  {"ts":0,"ph":"M","pid":149792,"name":"process_name","args":{"name":"[149792] collect2"}},
  {"ts":0,"ph":"M","pid":149792,"name":"thread_name","args":{"name":"[149792] collect2"}},
  {"ts":0,"ph":"M","pid":149793,"name":"process_name","args":{"name":"[149793] x86_64-linux-gn"}},
  {"ts":0,"ph":"M","pid":149793,"name":"thread_name","args":{"name":"[149793] x86_64-linux-gn"}},
  {"ts":15993488663803.713,"ph":"B","pid":149779,"name":"malloc"},
  {"ts":15993488663811.756,"ph":"E","pid":149779,"name":"malloc"},
      ...

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
Hmm.. Please wait. I will take care of one more.

**Comment by namhyung** [comment]
I found something about task name processing.  Could you please check [below patch](https://github.com/namhyung/uftrace/files/2360637/perf-Handle-COMM-event-properly.patch.txt)?

```diff
diff --git a/utils/fstack.c b/utils/fstack.c
index 5f425add..59772c73 100644
--- a/utils/fstack.c
+++ b/utils/fstack.c
@@ -1945,7 +1945,8 @@ static int __read_rstack(struct ftrace_file_handle *handle,
                task->rstack = get_perf_record(handle, perf);

                if (task->rstack->addr == EVENT_ID_PERF_COMM) {
-                       /* abuse task->args */
+                       task->rstack->more = 1;
+                       /* abuse task->args to save comm */
                        task->args.data = xstrdup(perf->u.comm.comm);
                        task->args.len  = strlen(perf->u.comm.comm);
                }
diff --git a/utils/perf.c b/utils/perf.c
index ca2dccdb..1cdac02a 100644
--- a/utils/perf.c
+++ b/utils/perf.c
@@ -464,6 +464,7 @@ struct uftrace_record * get_perf_record(struct ftrace_file_handle *handle,
        rec.type  = UFTRACE_EVENT;
        rec.time  = perf->time;
        rec.magic = RECORD_MAGIC;
+       rec.more  = 0;

        switch (perf->type) {
        case PERF_RECORD_FORK:
```

**Comment by namhyung** [comment]
Hmm.. [this patch](https://github.com/namhyung/uftrace/files/2361032/perf-Update-COMM-name-for-info.patch.txt) might fix it:

```diff
diff --git a/utils/fstack.c b/utils/fstack.c
index 8a097f14..acf8f43b 100644
--- a/utils/fstack.c
+++ b/utils/fstack.c
@@ -1950,6 +1950,9 @@ static int __read_rstack(struct ftrace_file_handle *handle,

        case PERF:
                task = get_task_handle(handle, perf->tid);
+               if (unlikely(task == NULL))
+                       pr_err_ns("cannot find task %d\n", perf->tid);
+
                task->rstack = get_perf_record(handle, perf);

                if (task->rstack->addr == EVENT_ID_PERF_COMM) {
diff --git a/utils/perf.c b/utils/perf.c
index d95571f3..f4d0a813 100644
--- a/utils/perf.c
+++ b/utils/perf.c
@@ -392,7 +392,7 @@ static int read_perf_event(struct ftrace_file_handle *handle,
                goto again;
        }

-       if (unlikely(get_task_handle(handle, perf->tid) == NULL))
+       if (unlikely(find_task(&handle->sessions, perf->tid) == NULL))
                goto again;

        perf->type = h.type;
```

**Comment by honggyukim** [comment]
It shows `as` and `ld` correctly with the fix above. Thanks!
```
$ uftrace info
# system information
# ==================
# program version     : v0.8.3-415-ga4d9 ( dwarf python tui perf sched )
# recorded on         : Fri Sep  7 16:22:26 2018
# cmdline             : uftrace record -t 1us --nest-libcall /usr/bin/gcc hello.c
# cpu info            : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
# number of cpus      : 40 / 40 (online / possible)
# memory info         : 0.2 / 62.5 GB (free / total)
# system load         : 9.33 / 10.82 / 12.00 (1 / 5 / 15 min)
# kernel version      : Linux 4.4.0-116-generic
# hostname            : intel20
# distro              : "Ubuntu 16.04.5 LTS"
#
# process information
# ===================
# number of tasks     : 5
# task list           : 149779(gcc), 149790(cc1), 149791(as), 149792(collect2), 149793(ld)
# exe image           : /usr/bin/gcc-5
# build id            : 5aac6cacaa39dbed27c08b758be6e60a27d2e5d3
# pattern             : regex
# exit status         : exited with code: 0
# elapsed time        : 0.274283083 sec
# cpu time            : 0.024 / 0.236 sec (sys / user)
# context switch      : 14 / 7 (voluntary / involuntary)
# max rss             : 21028 KB
# page fault          : 0 / 6028 (major / minor)
# disk iops           : 0 / 80 (read / write)
```

**Comment by namhyung** [comment]
Please consider the [below patch](https://github.com/namhyung/uftrace/files/2361132/dump-Fix-crash-on-chrome-dump-with-time-filter.patch.txt) too.

```diff
diff --git a/cmds/dump.c b/cmds/dump.c
index f363e929..cad787e4 100644
--- a/cmds/dump.c
+++ b/cmds/dump.c
@@ -1385,6 +1385,20 @@ static void dump_replay_event(struct uftrace_dump_ops *ops,

                ops->kernel_event(ops, kernel, kernel->last_read_cpu, rec);
        }
+       else if (is_event_record(task, rec)) {
+               struct uftrace_perf_reader perf = {
+                       .tid  = task->tid,
+                       .time = rec->time,
+               };
+
+               if (rec->addr == EVENT_ID_PERF_COMM) {
+                       memcpy(perf.u.comm.comm, task->args.data,
+                              sizeof(perf.u.comm.comm));
+                       perf.u.comm.pid  = task->t->pid;
+               }
+
+               ops->perf_event(ops, &perf, rec);
+       }
        else {
                struct uftrace_perf_reader *perf;

```

**Comment by namhyung** [comment]
This breaks some tests. please fix them.

**Comment by honggyukim** [comment]
Ah.. right. I've just requested it in #489.

**Pull request merged**
