### PR TITLE
doc: Add new badge for nightly-test

### PR DESCRIPTION
**Pull request by kangtegong**
Since uftrace is not using travis CI (for now),
New status badge for nightly test can be useful.

Signed-off-by: Kang Minchul <tegongkang@gmail.com>

### CODE REVIEW

**Review by namhyung — COMMENTED** [review]
Thanks for doing this.  I don't think we're gonna go back to the travis CI.  Please replace it.

**Comment by kangtegong** [comment]
Just replaced travis CI badge :)
By the way, do you think I should I remove `.travis.yml` as well?

**Comment by namhyung** [comment]
Oh right, please remove.

**Comment by kangtegong** [comment]
I just did :)

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
