### PR TITLE
uftrace: Introduce pre-commit and apply the changes

### PR DESCRIPTION
**Pull request by honggyukim**
This patch introduces pre-commit[1] to maintain the code quality in a
automated way.  It helps linting the code with some useful hooks
predefined in .pre-commit-config.yaml.

This patch also apples the changes by pre-commit such as removing all
the trailing whitespaces and so on.
```
  $ python3 -m pip install pre-commit

  $ pre-commit install
  pre-commit installed at .git/hooks/pre-commit

  $ pre-commit run -a
  Trim Trailing Whitespace.................................................Failed
  - hook id: trailing-whitespace
  - exit code: 1
  - files were modified by this hook
      ...
  Fix End of Files.........................................................Failed
  - hook id: end-of-file-fixer
  - exit code: 1
  - files were modified by this hook
      ...
```
After running this, it will show the result as follows.
```
  $ pre-commit run -a
  Check Yaml...............................................................Passed
  Fix End of Files.........................................................Passed
  Trim Trailing Whitespace.................................................Passed
  isort....................................................................Passed
```
[1] https://pre-commit.com
Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
It would be more useful if we can run this `pre-commit` in our CI.

**Review by namhyung — COMMENTED** [review]
Interesting.  What kind of hooks they have other than trim-trailing-whitespace and fix-EOF?

**Comment by honggyukim** [comment]
It can include `clang-format`, `clang-tidy`, spell checker and many other hooks. There are the list of hooks at https://pre-commit.com/hooks.html.

**Comment by honggyukim** [comment]
I've updated the PR as follows.

ChangeLog:
- pre-commit hooks run on travis CI
- upgrade travis machine to Ubuntu 18.04 to fix pre-commit installation problem
- enable clang compiler build as well

**Review by namhyung — APPROVED** [review]
LGTM!

**Pull request merged**
