### PR TITLE
tests: Change tests/runtest.py to match the pylint code style

### LINKED ISSUE #1497: warnings in pylint tests/runtest.py
We don't have to lint everything in our python script, but it'd be better to follow common rules in our python code. The following warnings from [pylint](https://github.com/PyCQA/pylint) are better to be fixed.
```
$ pylint tests/runtest.py
************* Module runtest
C: 96, 0: Line too long (97/80) (line-too-long)
C:141, 0: Line too long (101/80) (line-too-long)
C:181, 0: Line too long (82/80) (line-too-long)
C:195, 0: Line too long (82/80) (line-too-long)
C:205, 0: Line too long (86/80) (line-too-long)
C:212, 0: Line too long (82/80) (line-too-long)
C:229, 0: Line too long (82/80) (line-too-long)
C:238, 0: Line too long (84/80) (line-too-long)
C:243, 0: Line too long (92/80) (line-too-long)
C:245, 0: Line too long (82/80) (line-too-long)
C:251, 0: Line too long (85/80) (line-too-long)
C:252, 0: Line too long (83/80) (line-too-long)
C:257, 0: Line too long (96/80) (line-too-long)
C:259, 0: Line too long (90/80) (line-too-long)
C:276, 0: Line too long (82/80) (line-too-long)
C:393, 0: Line too long (110/80) (line-too-long)
C:551, 0: Line too long (81/80) (line-too-long)
C:581, 0: Line too long (88/80) (line-too-long)
C:582, 0: Line too long (88/80) (line-too-long)
C:597, 0: Line too long (85/80) (line-too-long)
C:598, 0: Line too long (85/80) (line-too-long)
C:599, 0: Line too long (85/80) (line-too-long)
C:620, 0: Line too long (90/80) (line-too-long)
C:622, 0: Line too long (85/80) (line-too-long)
C:741, 0: Line too long (85/80) (line-too-long)
C:771, 0: Line too long (93/80) (line-too-long)
C:777, 0: Line too long (82/80) (line-too-long)
C:796, 0: Line too long (81/80) (line-too-long)
C:797, 0: Line too long (82/80) (line-too-long)
C:799, 0: Line too long (92/80) (line-too-long)
C:809, 0: Line too long (103/80) (line-too-long)
C:810, 0: Line too long (81/80) (line-too-long)
C:900, 0: Line too long (88/80) (line-too-long)
W: 34, 8: No exception type(s) specified (bare-except)
W: 25, 8: Unused variable 'ELFCLASSNUM' (unused-variable)
W: 24, 8: Unused variable 'ELFCLASS64' (unused-variable)
W: 22, 8: Unused variable 'ELFCLASSNONE' (unused-variable)
W: 65, 8: No exception type(s) specified (bare-except)
C: 61,19: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
W: 96,23: Redefining name 'name' from outer scope (line 877) (redefined-outer-name)
W:147, 8: No exception type(s) specified (bare-except)
W:169, 8: No exception type(s) specified (bare-except)
W:172,20: Redefining name 'name' from outer scope (line 877) (redefined-outer-name)
W:226,27: Redefining name 'name' from outer scope (line 877) (redefined-outer-name)
W:296,12: No exception type(s) specified (bare-except)
W:316, 8: No exception type(s) specified (bare-except)
W:320,34: Unused argument 'ignored' (unused-argument)
W:351,12: No exception type(s) specified (bare-except)
W:333,34: Unused argument 'ignored' (unused-argument)
W:357,33: Unused argument 'ignored' (unused-argument)
W:385,32: Unused argument 'ignored' (unused-argument)
W:388, 8: Unused variable 'mode' (unused-variable)
W:436,20: Redefining name 'name' from outer scope (line 877) (redefined-outer-name)
W:427,12: Redefining name 'o' from outer scope (line 836) (redefined-outer-name)
W:428, 8: No exception type(s) specified (bare-except)
W:418,34: Unused argument 'ignored' (unused-argument)
W:459,20: Unused argument 'cflags' (unused-argument)
W:466, 8: Redefining name 'os' from outer scope (line 5) (redefined-outer-name)
W:479, 8: No exception type(s) specified (bare-except)
W:525,33: Unused argument 'frame' (unused-argument)
W:525,28: Unused argument 'sig' (unused-argument)
W:541,18: Redefining name 'name' from outer scope (line 877) (redefined-outer-name)
W:559,33: Unused argument 'frame' (unused-argument)
W:559,28: Unused argument 'sig' (unused-argument)
W:621,16: No exception type(s) specified (bare-except)
W:127, 8: Attribute 'debug' defined outside __init__ (attribute-defined-outside-init)
W:137, 8: Attribute 'port' defined outside __init__ (attribute-defined-outside-init)
W:682, 4: Redefining name 'tc' from outer scope (line 875) (redefined-outer-name)
W:686,39: Redefining name 'arg' from outer scope (line 823) (redefined-outer-name)
W:686,26: Redefining name 'flags' from outer scope (line 839) (redefined-outer-name)
W:692, 4: Redefining name 'tc' from outer scope (line 875) (redefined-outer-name)
W:686,33: Redefining name 'opts' from outer scope (line 836) (redefined-outer-name)
W:713,35: Redefining name 'shared' from outer scope (line 848) (redefined-outer-name)
W:723,43: Redefining name 'color' from outer scope (line 888) (redefined-outer-name)
W:723,50: Redefining name 'ftests' from outer scope (line 869) (redefined-outer-name)
W:751,28: Redefining name 'flags' from outer scope (line 839) (redefined-outer-name)
W:751,35: Redefining name 'ftests' from outer scope (line 869) (redefined-outer-name)
W:751,22: Redefining name 'opts' from outer scope (line 836) (redefined-outer-name)
W:770,22: Redefining name 'color' from outer scope (line 888) (redefined-outer-name)
W:770,29: Redefining name 'shared' from outer scope (line 848) (redefined-outer-name)
```
Once all the warnings are fixed, we can add pylint hook in our pre-commit.

### PR DESCRIPTION
**Pull request by sypark9646**
apply `black` for linting, and follow common rules in python code.
The following warnings from [pylint](https://github.com/PyCQA/pylint) are fixed.

If you want to find the full pylint warning, run the following command:
```
pylint tests/runtest.py 
```

And if you want to find a specific pylint warning(ex. W0613), you can run a command like this:
```
pylint tests/runtest.py --disable R,C,W,E --enable W0613
```

resolves #1497 
related #1396

### CODE REVIEW

**Comment by honggyukim** [comment]
Thanks, but it looks too many changes are applied in a single patch. Is it possible to apply each pylint violation one at a single commit then create multiple commits?

**Comment by sypark9646** [comment]
Oh I get it.
I'll split and re-commit as per warning, thanks!

**Comment by namhyung** [comment]
Can you please change the max line length from 80 to 100?

**Comment by sypark9646** [comment]
Okay, I'll incorporate your suggestion into the code! Thanks

**Comment by sypark9646** [comment]
The pylint warning you mentioned is left [W0613](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/unused-argument.html) (unused-argument),
If you need a commit to delete ignored arguments used in `simple_sort`, `report_sort`, `graph_sort`, `dump_sort`, `chrome_sort`, etc. I'd delete that, but I'm afraid it might be important, so I couldn't delete it now.

**Review by namhyung — APPROVED** [review]
LGTM, and it'd be nice if you could share the exact command line you ran to get these warnings.

**Comment by namhyung** [comment]
Oh, you already wrote the command line in the PR.  I'll merge the change then.

**Comment by namhyung** [comment]
Ugh, please put a blank line after the subject line later so that `git log --oneline` can show it properly.

I hate github displaying such a subject line without any warnings.

**Comment by honggyukim** [comment]
@sypark9646, You will understand what @namhyung mentioned by running `git log` and `git log --oneline`.

The commit message should have a separate commit title, which is written in a single line at the top.

For example, the your commit message is written as follows.
```
commit 8d8f168b1b57ab1de1a8f7a6b0404da6d7b0053e
Author:     Soyeon Park <sypark9646@gmail.com>
AuthorDate: Mon Sep 4 12:44:32 2023 +0900

    Pylint W0612: Unused variable
    Used when a variable is defined but not used.
    
    Signed-off-by: Soyeon Park <sypark9646@gmail.com>
```
But it should have a separate commit title in a single line. Because of this, the `git log --oneline` output looks weird.
```
$ git log --oneline 8d8f168b -1
8d8f168b Pylint W0612: Unused variable Used when a variable is defined but not used.
```
So the commit message should be changed with an empty line as follows.
```
commit 8d8f168b1b57ab1de1a8f7a6b0404da6d7b0053e
Author:     Soyeon Park <sypark9646@gmail.com>
AuthorDate: Mon Sep 4 12:44:32 2023 +0900

    tests: Pylint W0612: Unused variable

    Used when a variable is defined but not used.
    
    Signed-off-by: Soyeon Park <sypark9646@gmail.com>
```
It will show the commit log with `--oneline` properly as follows.
```
$ git log --oneline 8d8f168b -1
8d8f168b tests: Pylint W0612: Unused variable
```
This PR is already merged so we can't change it, but please keep that in mind for the next PR. Thanks.

**Comment by MichelleJin12** [comment]
Hello, @sypark9646,

In addition to Hongyu's comment, 
You don't need to add `.` to the end of the title of the [commit](https://github.com/namhyung/uftrace/pull/1810/commits/34a062c4417501d0a4d76b0037c61bec83ba070a) message.

Thank you for your contribution. :D

**Comment by sypark9646** [comment]
Ah thank you, I'll fix it right now. Do i have to create new pull request?

**Comment by namhyung** [comment]
Is there any checker doing this automatically?

**Comment by honggyukim** [comment]
There is https://github.com/conventional-changelog/commitlint but I haven’t had a chance to add it in our pre-commit hook yet.

**Pull request merged**
