### PR TITLE
slide: Add full dynamic tracing section

### PR DESCRIPTION
**Pull request by honggyukim**
Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
Please take a look at https://uftrace.github.io/slide/#full-dynamic-tracing.

**Comment by namhyung** [comment]
Actually it's not adding calls to `mcount` it replaces.  Hmm.. but it'd be more difficult to display and explain in the slide...

**Comment by honggyukim** [comment]
Do you think it'd better to change `mcount` to `__dentry__`?

**Comment by namhyung** [comment]
No, I think it'd be easier to understand to use `mcount`.

**Comment by honggyukim** [comment]
It actually goes to `__dentry__` but it calls `mcount_entry` inside so it seems reasonable.

**Comment by namhyung** [comment]
I'm ok with that part.  What I concerned was it overwrites the existing instructions instead of inserting to some (empty?) space.

**Comment by namhyung** [comment]
But now I'm ok with the current state - don't need to update..

**Pull request merged**
