### PR TITLE
doc/ko: Update korean document for script command

### PR DESCRIPTION
**Pull request by kpk0616**
There is a new script API `uftrace_event`, but it hasn't been updated
in Korean man page.  This patch is to update the Korean documentation.

Fixed: #1491
Signed-off-by: Euiseo Park <kpk0616@naver.com>

### CODE REVIEW

**Review by namhyung — APPROVED** [review]
LGTM

**Comment by honggyukim** [comment]
@kpk0616 Your author name looks weird. Please check again.
```
From d9acb45b87b3358c8e7e8403a1d769af4c58d20e Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?=EB=B0=95=EC=9D=98=EC=84=9C?=
 <70744494+kpk0616@users.noreply.github.com>
Date: Mon, 25 Jul 2022 19:22:33 +0900
Subject: [PATCH] doc/ko: Update korean document for script command

I applied change that was updated in the man page for `uftrace_event` API to Korean documentation.
Fixed: #1491
Signed-off-by: Euiseo Park <kpk0616@naver.com>
```
https://github.com/namhyung/uftrace/pull/1493.patch

**Review by honggyukim — CHANGES_REQUESTED** [review]
Please fix your name in the author properly.
```
From: =?UTF-8?q?=EB=B0=95=EC=9D=98=EC=84=9C?=
 <70744494+kpk0616@users.noreply.github.com>
```

**Comment by namhyung** [comment]
Looks like a UTF-8 encoded Korean name.

Btw, where can I see the raw commit message (for others?).  I think I can use the URL but wondering if there's a UI component for it already.

**Comment by honggyukim** [comment]
We can see the raw patch file by adding `.patch` postfix to the pull request URL.
- PR URL: https://github.com/namhyung/uftrace/pull/1493
- Raw patch format URL: https://github.com/namhyung/uftrace/pull/1493.patch

Likewise, we can also see the diff only by adding `.diff` postfix.
- Raw diff format URL: https://github.com/namhyung/uftrace/pull/1493.diff

**Comment by kpk0616** [comment]
I fixed my name in the author! Please check.

**Comment by honggyukim** [comment]
Please change the commit message as follows.
```
There is a new script API `uftrace_event`, but it hasn't been updated
in Korean man page.  This patch is to update the Korean documentation.

Fixed: #1491
Signed-off-by: Euiseo Park <kpk0616@naver.com>
```
The commit message convention is to have less than 72 characters in a single line.

**Comment by kpk0616** [comment]
I'm sorry for the delay in checking.
I just modified the commit message!

**Review by honggyukim — APPROVED** [review]
LGTM

**Pull request merged**
