### PR TITLE
utils: Make gray color to dark gray

### PR DESCRIPTION
**Pull request by honggyukim**
The current gray color still looks same as normal text color in some
environments.  This patch makes the gray to dark gray.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by namhyung** [comment]
Did you check it works as expected on putty, Ubuntu and Mac?

**Comment by honggyukim** [comment]
Yeap. It looks good in Windows putty, Ubuntu and Mac iterm terminals. But the color looks black in my Mac default terminal which is white background color.

**Comment by honggyukim** [comment]
That's the only problem but I don't use default Mac terminal. It's okay for me and Ubuntu and putty users but I'm not sure for others who use Mac default terminal.

**Comment by honggyukim** [comment]
Mac default terminal setting looks a bit different from others.

**Comment by honggyukim** [comment]
It looks good in Mac iterm, which I always use.

screen shot 2018-06-22 at 11 13 45 am

Hmm.. It's difficult to satisfy all the environments.

**Comment by honggyukim** [comment]
Thanks. 'bold black (1;30' satisfies all the environments including Windows putty, Ubuntu terminal, and Mac iterm and default terminal. Thanks very much!

**Comment by namhyung** [comment]
In a similar fashion why about changing read and blue as they use bold attribute actually?

**Comment by honggyukim** [comment]
Right. I'm not sure about it. Those colors seem to be used for report diff and error message for red.

**Comment by namhyung** [comment]
I think it's ok to change.

**Comment by honggyukim** [comment]
Do you mean to change this way?
```diff
diff --git a/utils/debug.c b/utils/debug.c
index f2cf383..4b2cd94 100644
--- a/utils/debug.c
+++ b/utils/debug.c
@@ -18,10 +18,10 @@
 #define TERM_COLOR_NORMAL      ""
 #define TERM_COLOR_RESET       "\033[0m"
 #define TERM_COLOR_BOLD                "\033[1m"
-#define TERM_COLOR_RED         "\033[1;31m"  /* bright red */
+#define TERM_COLOR_RED         "\033[91m"    /* bright red */
 #define TERM_COLOR_GREEN       "\033[32m"
 #define TERM_COLOR_YELLOW      "\033[33m"
-#define TERM_COLOR_BLUE                "\033[1;34m"  /* bright blue */
+#define TERM_COLOR_BLUE                "\033[94m"    /* bright blue */
 #define TERM_COLOR_MAGENTA     "\033[35m"
 #define TERM_COLOR_CYAN                "\033[36m"
 #define TERM_COLOR_GRAY                "\033[90m"    /* bright black */
```

**Comment by honggyukim** [comment]
Just updated. Thanks!

**Pull request merged**
