### PR TITLE
Add support for building and submitting Debian packages

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Add debian/* from thepaul/uftrace, updated for 0.10+ and python3.

The Debian and Ubuntu packages require an update, the current status is summarized here:
https://qa.debian.org/excuses.php?package=uftrace

deb packages can now be built on Debian/Ubuntu-based distros using debuild, sbuild and dpkg-buildpackage,
and uploaded to Debian.
    
For this, create an new directroy and in it, git clone this into a
directory named uftrace-0.10.54 (version set in debian/changelog),
and run tar cvfz uftrace_0.10.54.orig.tar.gz uftrace-0.10.54/

For building in debian/unstable (sid) schroot, install and run
sbuild-debian-developer-setup and then run sbuild. See:
https://wiki.debian.org/sbuild

### CODE REVIEW

**Comment by namhyung** [comment]
Thanks for working on this.  While I don't want to have it in the uftrace source tree, it might be good to have a standard repo to maintain debian (and maybe others too) packaging.   @honggyukim what about adding it to github.com/uftrace/debian ?

**Comment by honggyukim** [comment]
> @honggyukim what about adding it to github.com/uftrace/debian

I can do that. But how about apply these commits into a separate branch such as `package/debian`?

**Comment by bernhardkaindl** [comment]
> > @honggyukim what about adding it to github.com/uftrace/debian
> 
> I can do that. But how about apply these commits into a separate branch such as `package/debian`?

This is an very good - even excellent idea! That way, the package/debian branch can be it's own master branch for creating a new debian package.

In this branch, we/you'd only have a merge/rebase correctly debian-buildable revisions, and when an upload to debian for a new debian package is done, you could tag that commit.

I like that idea very much.

**Comment by namhyung** [comment]
I don't know if we can get a PR for this specific branch then.

**Comment by honggyukim** [comment]
> I don't know if we can get a PR for this specific branch then.

It's possible if the PR requester changed the target branch from `master` to `package/debian`.

However, if accepting this changes is really helpful for debian packaging, then it'd also be good to have it in `master` branch under `misc/package/debian`. The only concern is the number of commits, but we can squash them into a few commits and apply them into `master`. I'm fine either way.

**Comment by namhyung** [comment]
But I'm afraid that debian packaging system might require a specific directory structure like the 'debian' directory should be in the root.

**Comment by bernhardkaindl** [comment]
Honggyu Kim wrote:
>
>     I don't know if we can get a PR for this specific branch then.
>
> It's possible if the PR requester changed the target branch from 
> |master| to |package/debian|.
>
> However, if accepting this changes is really helpful for debian 
> packaging, then it'd also be good to have it in |master| branch under 
> |misc/package/debian|. The only concern is the number of commits, but 
> we can squash them into a few commits and apply them into |master|. 
> I'm fine either way.
>
The advantages of having the debian package sources in the master branch 
are like this:

1st Class of advantages:

# Whoever checks out the code and works with it can build his own local 
debian package with his changes.

This is very helpful in several situations:

## You are a devops engineer in a company who is rolling out packages 
for use by in devops.

What you want is that you have all rolled-out-software installed as s 
package, so when you install or update the rolled-out-software, you just 
put the new package into the package pool of the system.

## You are someone building containers for development, testing or 
production

Likewise, what you want is a package to install in e.g. the Dockerfile, 
together will all other special packages fetched and/or installed in the 
container

## You are a developer who wants to have a clean system

When you want to keep your system really clean, one should avoid 
installing stuff by "make install" without any tracking so uninstalls 
and updates are easier.

What you do, is instead of "make install" you build the package and 
install the package.

---

2nd advantage:

If soneone is working on a new feature, he himself can also test the 
packages created and update the packaging files accordingly

Examples are: Adding new dependencies, how to run the tests, and 
ensuring that the tests also run inside the packaing system (which they 
currently don't do well enough)

3rd advantage:

In deban/control, you could update these entries to your repo's URL's 
master bramch:

Vcs-Git: https://github.com/bernhardkaindl/uftrace -b deb

Vcs-Browser: https://github.com/bernhardkaindl/uftrace/tree/deb

These URLs are linked in the debian package tracker here:

On https://tracker.debian.org/pkg/uftrace

> Debian Package Tracker <https://tracker.debian.org/>
>
> Register <https://tracker.debian.org/accounts/register/> | Log in 
> <https://tracker.debian.org/accounts/login/>
>
>
>   uftrace
>
>
>           Traces and analyzes execution of programs written in C/C++
>
> general
>
>   * *source:* uftrace <https://packages.debian.org/src:uftrace> (main)
>   * *version:* 0.9.4-0.2
>   * *maintainer:* paul cannon
>     <https://qa.debian.org/developer.php?email=pik%40debian.org> (DMD
>     <https://udd.debian.org/dmd/?pik%40debian.org#todo>) (LowNMU
>     <https://wiki.debian.org/LowThresholdNmu>)
>   * *arch:* amd64 arm64 armhf i386
>   * *std-ver:* 4.4.0
>   * *VCS:* Git <https://github.com/thepaul/uftrace> (Browse
>     <https://github.com/thepaul/uftrace/tree/deb>, QA
>     <https://qa.debian.org/cgi-bin/vcswatch?package=uftrace>)
>     ^^^^^^^^^^^^^^^^---------------------------------- here they are
>
For Uubuntu, it is found here:

https://packages.ubuntu.com/source/impish/uftrace

> Debian Package Source Repository (VCS:Git 
> <https://packages.ubuntu.com/impish/git-core>)
>     https://github.com/thepaul/uftrace -b deb
>     <https://github.com/thepaul/uftrace%20-b%20deb>
> Debian Package Source Repository (Browsable)
>     https://github.com/thepaul/uftrace/tree/deb
>     <https://github.com/thepaul/uftrace/tree/deb> 
This means anyone who knows or uses Debian or Ubuntu can go to 
http://packages.debian.org or http://packages.ubuntu.com lookup the 
package, and find the info where the upstream maintains his sources.

Besides installing, also has the info on building the package in the 
debian directory in that repo.

Note:

On http://packages.debian.org you have to select "unstable" when 
searching the package directories to find uftrace because of the 
neglected build problems in Debian.

Then, on   https://packages.debian.org/sid/uftrace - you click the link 
"Developer Information" to go to the package tracker:

>
>       Debian Resources:
>
>   * Bug Reports <https://bugs.debian.org/uftrace>
>   * Developer Information <https://tracker.debian.org/uftrace>
>
Best regards, Bernhard

**Comment by honggyukim** [comment]
It seems @thepaul is preparing `uftrace-v0.10` release at [his deb branch](https://github.com/thepaul/uftrace/tree/deb).  The `debian` directory looks like https://github.com/thepaul/uftrace/tree/deb/debian.

I personally think it might be useful to maintain his `debian` directory in `master` because debian package can be the most important package target if @thepaul is fine with it.

**Comment by namhyung** [comment]
@thepaul can you please share your opinion?

**Comment by thepaul** [comment]
It might be useful for you to maintain the `debian` directory in master, but you would need to change at least a few things. This document might help: [What is the difference between a native Debian package and a non-native package?](https://wiki.debian.org/DebianMentorsFaq#What_is_the_difference_between_a_native_Debian_package_and_a_non-native_package.3F)

Also, you'd probably want to be aware that I or other packagers might still add to what you have in `debian/`, or change it, for whatever our target distro is. For example, the MOTU team with Ubuntu might make changes to it for one of the reasons shown [here](https://wiki.ubuntu.com/Ubuntu/ForDebianDevelopers#Why_does_Ubuntu_need_to_change_my_packages.3F__What_kind_of_changes_are_made.3F). And there are quite a few other Debian-derivative distros, all of which have specialized needs. If packagers do make changes, they would be maintained as a patch against your releases (like `uftrace_0.9.3-1.debian.tar.xz`). The packager would add an appropriate packageversion suffix part back on to the version number as part of that patch.

If all of that makes sense, you can feel free to maintain packaging in your master branch. Otherwise, I don't really recommend it. It often just adds to more confusion for everyone.

**Comment by namhyung** [comment]
Actually I don't want to add the packaging stuff in the master branch.  But some users want to have a place to track packaging status and to keep it up to date in case maintainers are busy.  We considered having a separate repository or branch too.

**Comment by namhyung** [comment]
Yeah, I think it'd be nice if you could take PRs from others.  Maybe we could have a wiki page to organize packaging efforts for various distros.

**Comment by namhyung** [comment]
So I'm closing this.  @bernhardkaindl please contact to @thepaul if you want to update packaging.  And please do it for v0.11!

**Pull request closed without merging**
