### PR TITLE
Rename 'ftrace' residues -> 'uftrace'

### PR DESCRIPTION
**Pull request by Taeung**
This is trivial patches:
 - Rename 'ftrace' residues on some comments to 'uftrace'
 - Rename TestBase.ftrace to TestBase.uftrace_cmd to be more readable

### CODE REVIEW

**Comment by Taeung** [comment]
In addition, we need to modify the below two line (Makefile:45, 54) ?
I thought ftrace.data and gmon.out aren't needed anymore.
```
  $ grep ftrace
tests/arch/x86_64/Makefile
45:	$(RM) $(ALL_TARGETS) *.o ftrace.data* gmon.out *-diff

tests/arch/arm/Makefile
54:	$(RM) $(ALL_TARGETS) *.o ftrace.data* gmon.out *-diff
```
And need to modify the below lines because of old 'ftrace' ?
https://github.com/namhyung/uftrace/blob/master/tests/arch/arm/Makefile#L3
https://github.com/namhyung/uftrace/blob/master/tests/arch/x86_64/Makefile#L3

**Comment by namhyung** [comment]
> I thought ftrace.data and gmon.out aren't needed anymore.

Yep, it should be change to `uftrace.data`, but please keep the `gmon.out` as it can be made during some testing when built with `-pg`.

> And need to modify the below lines because of old 'ftrace' ?

Yes please.

**Comment by Taeung** [comment]
Yep, I got it 😄

**Comment by Taeung** [comment]
I changed this PR !

**Pull request merged**
