### PR TITLE
check-deps:changed gelf function in __have_libelf.c

### PR DESCRIPTION
**Pull request by JangSoJin**
The currently reflected __have_libelf.c may cause errors during compilation if unused variables(GElf_Ehdr ehdr) are declared.

so i would like to modify it as follows :

```C
#include <gelf.h>
#include <libelf.h>

int main(void)
{
      Elf *elf;

      elf_version(EV_CURRENT);

      /* check that the gelf function */
      elf = elf_begin(0, ELF_C_READ, NULL);
      gelf_checksum(elf);
      elf_end(elf);

      return 0;
}
```

Thanks,
Fixed : #1869 (gcc -Wall -Werror: libelf: [ OFF ] even when libelf-devel is installed)

### CODE REVIEW

**Comment by vt-alt** [comment]
I only wonder why you break formatting of the original file from a tab to 6 spaces.

**Comment by JangSoJin** [comment]
oh, okay thanks @vt-alt 
i forgot to check format in the procedure, sorry. 
i’ll fix and push again.

**Comment by JangSoJin** [comment]
[Re-upload] 

The currently reflected __have_libelf.c may cause errors during compilation if unused variables(GElf_Ehdr ehdr) are declared.
so i would like to modify it as follows :

```C
#include <gelf.h>
#include <libelf.h>

int main(void)
{
      Elf *elf;

      elf_version(EV_CURRENT);

      /* check that the gelf function */
      elf = elf_begin(0, ELF_C_READ, (Elf *)0);
      gelf_checksum(elf);
      elf_end(elf);

      return 0;
}

```

FYI, when i tried `elf_begin(0, ELF_C_READ, NULL)`, the result was incorrect, so i changed `elf_begin(0, ELF_C_READ, (Elf *)0)`.
(i don't understand what the difference is between,,)
※ if it needs to be modified, please let me know.

Sorry for the inconvenience!
Thanks,
Fixed : #1869 (gcc -Wall -Werror: libelf: [ OFF ] even when libelf-devel is installed)

**Comment by gichoel** [comment]
First, Thank you for your efforts to resolve this issue.

However, There are a few rules to follow to write a good readable commit message, and there are three things you should fix in your commit message:
  1. The first letter of the title, except for the 'type' part, should be capitalized.
  2. The title should be 50 characters or less, but currently exceeds 50 characters, including spaces.
  3. The body should also be 72 characters or less, but there are lines of body that exceed 72 characters.

Could you please make this change?

**Comment by JangSoJin** [comment]
Thanks, @gichoel 
i made the changes based on your feedback, thanks for the support!

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request closed without merging**
