### PR TITLE
doc: Move -H option to COMMON ANALYSIS OPTION

### PR DESCRIPTION
**Pull request by kangtegong**
Since -H/--hide option is only supported for analysis commands,
this commit moves the option to right location in man pages.

Fixed: #1261

Signed-off-by: Kang Minchul <tegongkang@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
Can you just move them to the top of `COMMON ANALYSIS OPTIONS`?

**Comment by kangtegong** [comment]
Ok, I just did

**Review by honggyukim — APPROVED** [review]
Thanks for the fix!

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
