### PR TITLE
doc: Change NEWS to NEWS.md and add issue/pr links

### PR DESCRIPTION
**Pull request by honggyukim**
It can be preferable to having markdown NEWS and add github
issue/pr number to NEWS.md.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>

### CODE REVIEW

**Comment by namhyung** [comment]
Do we really need to add the links manually?

**Comment by honggyukim** [comment]
I think it'd be clearer if we have links for each item. If you don't want, I can drop this.

**Comment by namhyung** [comment]
Yeah, I think keeping the issue/pr number is enough.

**Comment by honggyukim** [comment]
> Yeah, I think keeping the issue/pr number is enough.

Then we can just use plain text `README` with issue/pr numbers is enough.

**Comment by honggyukim** [comment]
I will close this then.

**Pull request closed without merging**
