### PR TITLE
build: Fix compile warning message

### PR DESCRIPTION
**Pull request by keepgoingxxx**
Python.h should not be on the first line.
Python.h needs to be rearranged.

issue: #1648

Signed-off-by: Jin Jang <keepgoingxxx@gmail.com>

### CODE REVIEW

**Review by namhyung — COMMENTED** [review]
Why do you think it should not be on the first line?  Actually the python document says we must include Python.h before any standard headers.

https://docs.python.org/3/c-api/intro.html#include-files

**Comment by MichelleJin12** [comment]
Hello, @keepgoingxxx Thank you for your contribution. :D

You missed the sign-off, so please amend the commit message. For more details, check out https://github.com/namhyung/uftrace/pull/1768/checks?check_run_id=15265603135.
You can try the command below
```sh
git commit --amend -s
git push --force
```

**Comment by keepgoingxxx** [comment]
@MichelleJin12, Thank you 😊

**Comment by MichelleJin12** [comment]
@honggyukim,
I think that this PR can fix https://github.com/namhyung/uftrace/issues/1648, and https://github.com/namhyung/uftrace/issues/1724.

Would you be willing to review it? Thank you. :D

**Review by namhyung — COMMENTED** [review]
I think simply `#undef _XOPEN_SOURCE` before `#include <Python.h>` is fine.  Do you see a problem with that?

**Comment by keepgoingxxx** [comment]
@namhyung,

uftrace uses 600 as the value for _XOPEN_SOURCE.
However, python uses 700 as the _XOPEN_SOURCE value. 
I don't have much knowledge about _XOPEN_SOURCE, so I wonder if I can use the value of 700.

If _XOPEN_SOURCE can be set to 700, I think it can be solved by simply unset as you said.
Please give me your opinion.

**uftrace**
```
libtraceevent/TRACEEVENT-CFLAGS:1: -D_XOPEN_SOURCE=600
``` 

**python**
```
  CC FPIC  python/trace-python.op
In file included from /usr/include/python3.11/pyconfig.h:6,
                 from /usr/include/python3.11/Python.h:12,
                 from /home/install/uftrace/python/trace-python.c:15:
/usr/include/python3.11/pyconfig-64.h:1867: warning: "_XOPEN_SOURCE" redefined
 1867 | #define _XOPEN_SOURCE 700
```

**Comment by namhyung** [comment]
libtraceevent is old, and I think it's only used for libtraceevent build so it'd be fine to use python's one.

**Comment by keepgoingxxx** [comment]
@namhyung, 
 
Could you please review the commit?

**Review by namhyung — COMMENTED** [review]
Looks good.  But please update the commit message not to exceed 72 characters on a line.  Also make 'fixed:' to 'Fixed:'.

**Comment by honggyukim** [comment]
In addition, please give an empty space after `:` in the commit message.
```diff
-build:Fix compile warning message
+build: Fix a compile warning message
```

**Comment by keepgoingxxx** [comment]
Sorry about the inconvenience.
Could you please review the commit?

**Review by namhyung — APPROVED** [review]
Hmm.. I cannot reproduce it anymore.  But your change also works well with my current setup, so LGTM!

**Pull request merged**
