### PR TITLE
Dump: Adding nanoseconds precision for "ts" field in Trace Event Format output

### PR DESCRIPTION
**Pull request by abenbachir**
chrome://tracing support nanoseconds.

### CODE REVIEW

**Comment by abenbachir** [comment]
I wanted to use defaultTimeUnit:"ns" configuration discussed at this thread https://github.com/google/trace-viewer/issues/624. but i think adding decimal point precision is more simple.

**Comment by abenbachir** [comment]
There is an bug happing in chrome://tracing with the decimal precision as in the picture 
trace-with-ns-decimal-precision

When I removed the decimal precision and used only nanseconds "frs->time" with "defaultTimeUnit":"ns"  the call stack aligned very will see picture
trace-with-defaulttimeunit-ns

This is the both trace file related to both previous pictures [trace-decimal-precision.json](https://gist.github.com/abenbachir/da7543d6f796348b37b09e74308d92bf), [trace-with-defaultTimeUnit.json](https://gist.github.com/abenbachir/dc9d94e638c1885eb82d0b9ab52cfd59)


@namhyung I think we should use the attribute "defaultTimeUnit":"ns" and only use nanoseconds what do you think ?.

**Comment by namhyung** [comment]
@honggyukim Could you please take a look?

**Comment by abenbachir** [comment]
@namhyung it looks like @honggyukim is not responding

**Comment by namhyung** [comment]
@abenbachir sorry for late response.

I was off due to the one of the biggest holiday in Korea - luna new year.  I bet @honggyukim is same.  I'll try to check it by myself today.  Thanks!

**Comment by honggyukim** [comment]
@abenbachir Sorry for answering late. I will check it and answer back to you today.

**Comment by honggyukim** [comment]
@abenbachir Please apply the patch below, then you will see the problem is gone.
```
diff --git a/cmd-dump.c b/cmd-dump.c
index 572805d..0496366 100644
--- a/cmd-dump.c
+++ b/cmd-dump.c
@@ -598,7 +598,7 @@ static void print_chrome_footer(struct uftrace_dump_ops *ops,
        ctime_r(&statbuf.st_mtime, buf);
        buf[strlen(buf) - 1] = '\0';
 
-       pr_out("\n], \"metadata\": {\n");
+       pr_out("\n], \"displayTimeUnit\": \"ns\", \"metadata\": {\n");
        if (handle->hdr.info_mask & (1UL << CMDLINE))
                pr_out("\"command_line\":\"%s\",\n", handle->info.cmdline);
        pr_out("\"recorded_time\":\"%s\"\n", buf);
```
I found that the original name was "defaultTimeUnit":"ns" but it has been renamed to "displayTimeUnit":"ns". So please test it and let me know if it works for you.

**Comment by honggyukim** [comment]
@abenbachir You can find the formal document for trace event format from the link below:

https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit

**Comment by namhyung** [comment]
@honggyukim thanks for checking!

@abenbachir please also add your sign-off in the commit message after reading doc/contributing.md, thanks!

**Comment by abenbachir** [comment]
Thanks @honggyukim for the help it works now.
@namhyung I pushed my changes.

**Comment by namhyung** [comment]
@abenbachir thanks for your persistence!

**Pull request merged**
