### PR TITLE
Fix error on aarch64 with binutils2.35.1.

### PR DESCRIPTION
**Pull request by leimaohui**
WARN: child terminated by signal: 11: Segmentation fault

Signed-off-by: Lei Maohui <leimaohui@cn.fujitsu.com>

### CODE REVIEW

**Comment by leimaohui** [comment]
Without this patch, the program which uftrace wants to trace won't be executed. 
By comparing the correct situation, I found that the plthook_addr is not correct :
`found GOT at 0xaaaad50e9fe8 (base_addr + 0x10fe8)
module id = 0xffff9fcde280, PLT resolver = 0xffff9fcbbc58
p 3-4 got_idx = 3, i = 0
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[3] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 4, i = 1
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[4] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 5, i = 2
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[5] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 6, i = 3
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[6] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 7, i = 4
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[7] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 8, i = 5
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[8] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
p 3-4 got_idx = 9, i = 6
p 3-5 resolved_addr = 0xd50d96f0  plthook_addr = 0xd50d96e0
restore GOT[9] from "__cxa_finalize"(0xaaaad50d96f0) to PLT(base + 0x6e0)
mcount setup done
WARN: child terminated by signal: 11: Segmentation fault`

**Comment by namhyung** [comment]
But I guess your patch would make a trouble with earlier versions.  Could you please dump the start of the .plt section (PLT0) both in Ubuntu 20.04 and 20.10?

**Comment by leimaohui** [comment]
> But I guess your patch would make a trouble with earlier versions. 

Yes,  It‘ really a problem. I have test this patch on old environment, uftrace can't work.  
Should the next version of uftrace limit the version of binutils?

> Could you please dump the start of the .plt section (PLT0) both in Ubuntu 20.04 and 20.10?

I'm sorry, but I met this problem on my In-House Embedded Linux Distro based on Yocto(http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/uftrace/uftrace_0.9.4.bb?h=master), and I don't have Ubuntu of aarch64.
So, I dumped a binary on different versions of my Distro with different binutils. I don't know whether it is the data that you want?

With old binutils(2.35)：
```
root # readelf -a  a.out

  [12] .plt              PROGBITS         00000000000006c0  000006c0
       0000000000000080  0000000000000010  AX       0     0     16


root # hexdump -C a.out
......
000006c0  f0 7b bf a9 90 00 00 90  11 fe 47 f9 10 e2 3f 91  |.{........G...?.|
000006d0  20 02 1f d6 1f 20 03 d5  1f 20 03 d5 1f 20 03 d5  | .... ... ... ..|
000006e0  90 00 00 b0 11 02 40 f9  10 02 00 91 20 02 1f d6  |......@..... ...|
000006f0  90 00 00 b0 11 06 40 f9  10 22 00 91 20 02 1f d6  |......@..".. ...|
00000700  90 00 00 b0 11 0a 40 f9  10 42 00 91 20 02 1f d6  |......@..B.. ...|
00000710  90 00 00 b0 11 0e 40 f9  10 62 00 91 20 02 1f d6  |......@..b.. ...|
00000720  90 00 00 b0 11 12 40 f9  10 82 00 91 20 02 1f d6  |......@..... ...|
00000730  90 00 00 b0 11 16 40 f9  10 a2 00 91 20 02 1f d6  |......@..... ...|
......
```

With old binutils(2.36.1)：
```
root # readelf -a  a.out
......
  [12] .plt              PROGBITS         00000000000006f0  000006f0
       0000000000000090  0000000000000000  AX       0     0     16
......

root # hexdump -C a.out
......
000006f0  f0 7b bf a9 90 00 00 90  11 fe 47 f9 10 e2 3f 91  |.{........G...?.|
00000700  20 02 1f d6 1f 20 03 d5  1f 20 03 d5 1f 20 03 d5  | .... ... ... ..|
00000710  90 00 00 b0 11 02 40 f9  10 02 00 91 20 02 1f d6  |......@..... ...|
00000720  90 00 00 b0 11 06 40 f9  10 22 00 91 20 02 1f d6  |......@..".. ...|
00000730  90 00 00 b0 11 0a 40 f9  10 42 00 91 20 02 1f d6  |......@..B.. ...|
00000740  90 00 00 b0 11 0e 40 f9  10 62 00 91 20 02 1f d6  |......@..b.. ...|
00000750  90 00 00 b0 11 12 40 f9  10 82 00 91 20 02 1f d6  |......@..... ...|
00000760  90 00 00 b0 11 16 40 f9  10 a2 00 91 20 02 1f d6  |......@..... ...|
00000770  90 00 00 b0 11 1a 40 f9  10 c2 00 91 20 02 1f d6  |......@..... ...|
......
```

**Comment by honggyukim** [comment]
> Could you please dump the start of the .plt section (PLT0) both in Ubuntu 20.04 and 20.10?

Hi @leimaohui, I think @namhyung is asking to dump  it using `objdump -d` to see the instructions of `.plt` section.

I don't know if it's possible from your side but if you can share the binaries, then we can better investigate the problem.

**Comment by leimaohui** [comment]
Ok， I got it!
The following is the output of objdump -d :

Old Distro(binutils 2.35):
```
root # objdump -d a.out
......
Disassembly of section .plt:

00000000000006f0 <.plt>:
 6f0:   a9bf7bf0        stp     x16, x30, [sp, #-16]!
 6f4:   90000090        adrp    x16, 10000 <__FRAME_END__+0xf4a4>
 6f8:   f947fe11        ldr     x17, [x16, #4088]
 6fc:   913fe210        add     x16, x16, #0xff8
 700:   d61f0220        br      x17
 704:   d503201f        nop
 708:   d503201f        nop
 70c:   d503201f        nop

```
New Distro(binutils 2.36.1):
```
Disassembly of section .plt:

00000000000006f0 <.plt>:
 6f0:   a9bf7bf0        stp     x16, x30, [sp, #-16]!
 6f4:   90000090        adrp    x16, 10000 <__FRAME_END__+0xf48c>
 6f8:   f947fe11        ldr     x17, [x16, #4088]
 6fc:   913fe210        add     x16, x16, #0xff8
 700:   d61f0220        br      x17
 704:   d503201f        nop
 708:   d503201f        nop
 70c:   d503201f        nop

```

**Comment by leimaohui** [comment]
> I don't know if it's possible from your side but if you can share the binaries, then we can better investigate the problem.

I don't know how to share a binary here. Or by mail?

**Comment by namhyung** [comment]
You can add the file in the comment.  "Attach files by dragging & dropping, selecting or pasting them."

**Comment by honggyukim** [comment]
> You can add the file in the comment. "Attach files by dragging & dropping, selecting or pasting them."

For security reasons, github might not allow to attach executable binaries but you can rename the binary to add a postfix to something else. For example, if you have an executable binary `a.out`, then rename it to `a.out.txt` and it can be uploaded here in the comment windows.

**Comment by leimaohui** [comment]
[Uploading a.out.txt…]()

Thanks, I renamed a.out, and have uploaded it.

**Comment by leimaohui** [comment]
I found the other issue on aarch64. I try to trace a binary which build from a *.cpp file. I got the following error:
```
root # cat test2.cpp
#include <iostream>
using namespace std;
int main() {
    cout << "Hello World!\n";
    return 0;
}
root # g++ test2.cpp -pg
root #
root # uftrace --debug record a.out
uftrace: checking binary a.out
uftrace: removing uftrace.data.old directory
uftrace: using /usr/lib64/libmcount.so library for tracing
uftrace: creating 1 thread(s) for recording
mcount: initializing mcount library
plthook: setup PLT hooking "/home/root/a.out"
mcount: mcount setup done
mcount: new session started: 22edc9fc40111415: a.out
WARN: child terminated by signal: 11: Segmentation fault
uftrace: reading uftrace.data/task.txt file
uftrace: flushing /uftrace-22edc9fc40111415-2747-000
root #
```


I opened the debug info, found that plt_entsize seemed not correct: 
```
symbol: [1] P 8a0 + 0     _mcount
symbol: [2] P 8a0 + 0     __cxa_finalize
symbol: [3] P 8a0 + 0     __libc_start_main
symbol: [4] P 8a0 + 0     std::operator<<
symbol: [5] P 8a0 + 0     __cxa_atexit
symbol: [6] P 8a0 + 0     __monstartup
symbol: [7] P 8a0 + 0     std::ios_base::Init::Init
symbol: [8] P 8a0 + 0     abort
symbol: flags & SYMTAB_FL_ADJ_OFFSET 2-16
symbol: loaded 8 symbols
symbol: merge two symbol tables (left = 15, right = 8)
symbol: updating symbol name using dynamic symbols
symbol: update symbol name to __gmon_start__ 
```

```
Disassembly of section .plt:

0000000000000890 <.plt>:
 890:   a9bf7bf0        stp     x16, x30, [sp, #-16]!
 894:   b0000090        adrp    x16, 11000 <__FRAME_END__+0x101c4>
 898:   f947fe11        ldr     x17, [x16, #4088]
 89c:   913fe210        add     x16, x16, #0xff8
 8a0:   d61f0220        br      x17
 8a4:   d503201f        nop
 8a8:   d503201f        nop
 8ac:   d503201f        nop

00000000000008b0 <_mcount@plt>:
 8b0:   d0000090        adrp    x16, 12000 <_mcount@GLIBC_2.18>
 8b4:   f9400211        ldr     x17, [x16]
 8b8:   91000210        add     x16, x16, #0x0
 8bc:   d61f0220        br      x17

00000000000008c0 <__cxa_finalize@plt>:
 8c0:   d0000090        adrp    x16, 12000 <_mcount@GLIBC_2.18>
 8c4:   f9400611        ldr     x17, [x16, #8]
 8c8:   91002210        add     x16, x16, #0x8
 8cc:   d61f0220        br      x17

00000000000008d0 <__libc_start_main@plt>:
 8d0:   d0000090        adrp    x16, 12000 <_mcount@GLIBC_2.18>
 8d4:   f9400a11        ldr     x17, [x16, #16]
 8d8:   91004210        add     x16, x16, #0x10
 8dc:   d61f0220        br      x17

00000000000008e0 <_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@plt>:
 8e0:   d0000090        adrp    x16, 12000 <_mcount@GLIBC_2.18>
 8e4:   f9400e11        ldr     x17, [x16, #24]
 8e8:   91006210        add     x16, x16, #0x18
 8ec:   d61f0220        br      x17

00000000000008f0 <__cxa_atexit@plt>:
 8f0:   d0000090        adrp    x16, 12000 <_mcount@GLIBC_2.18>
 8f4:   f9401211        ldr     x17, [x16, #32]
 8f8:   91008210        add     x16, x16, #0x20
 8fc:   d61f0220        br      x17

0000000000000900 <__monstartup@plt>:
```

So, I tried to fix this bug by the following patch, but uftrace hangs up:

```
diff --git a/utils/symbol.c b/utils/symbol.c
index 62284f78..3d28df09 100644
--- a/utils/symbol.c
+++ b/utils/symbol.c
@@ -560,6 +560,7 @@ int load_elf_dynsymtab(struct symtab *dsymtab, struct uftrace_elf_data *elf,
        }
        else if (elf->ehdr.e_machine == EM_AARCH64) {
                plt_addr += 16;    /* AARCH64 PLT0 size is 32 */
+               plt_entsize = 16;
        }
        else if (elf->ehdr.e_machine == EM_386) {
                plt_entsize += 12;

```

With above patch, the debug output is the the following:
```
......
prev_addr = 0xb86a68a0, plt_entsize  = 0x10
symbol: [1] P aaaab86a68b0 + 16    _mcount
prev_addr = 0xb86a68b0, plt_entsize  = 0x10
symbol: [2] P aaaab86a68c0 + 16    __cxa_finalize
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a68c0, plt_entsize  = 0x10
symbol: [3] P aaaab86a68d0 + 16    __libc_start_main
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a68d0, plt_entsize  = 0x10
symbol: [4] P aaaab86a68e0 + 16    std::operator<<
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a68e0, plt_entsize  = 0x10
symbol: [5] P aaaab86a68f0 + 16    __cxa_atexit
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a68f0, plt_entsize  = 0x10
symbol: [6] P aaaab86a6900 + 16    __monstartup
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a6900, plt_entsize  = 0x10
symbol: [7] P aaaab86a6910 + 16    std::ios_base::Init::Init
load_dyn_symbol !=STN_UNDEF
prev_addr = 0xb86a6910, plt_entsize  = 0x10
symbol: [8] P aaaab86a6920 + 16    abort
symbol: loaded 8 symbols
found GOT at 0xaaaab86b7fe8 (base_addr + 0x11fe8)
module id = 0xffff8e2f7280, PLT resolver = 0xffff8e2d4c58
find_got 1-11
restore_plt_functions 1, dsymtab->nr_sym  = 8
overwrite GOT[3] to 0xffff8e29dc04 (_mcount)
restore_plt_functions 2
restore_plt_functions 2
restore_plt_functions 3
resolved_addr = 0xb86a6890, plthook_addr =0xb86a68a0
plthook: restore GOT[4] from "__cxa_finalize"(0xaaaab86a6890) to PLT(base + 0x8a0)
resolved_addr = 0xb86a6890, plthook_addr =0xb86a68a0
plthook: restore GOT[5] from "__libc_start_main"(0xaaaab86a6890) to PLT(base + 0x8a0)
resolved_addr = 0xb86a6890, plthook_addr =0xb86a68a0
plthook: restore GOT[6] from "std::operator<<"(0xaaaab86a6890) to PLT(base + 0x8a0)
resolved_addr = 0x8de7dae0, plthook_addr =0xb86a68a0
plthook: restore GOT[7] from "__cxa_atexit"(0xffff8de7dae0) to PLT(base + 0x8a0)
resolved_addr = 0x8e2849f4, plthook_addr =0xb86a68a0
plthook: restore GOT[8] from "__monstartup"(0xffff8e2849f4) to PLT(base + 0x8a0)
resolved_addr = 0xb86a6890, plthook_addr =0xb86a68a0
plthook: restore GOT[9] from "std::ios_base::Init::Init"(0xaaaab86a6890) to PLT(base + 0x8a0)
restore_plt_functions 3
resolved_addr = 0xb86a6890, plthook_addr =0xb86a68a0
plthook: restore GOT[10] from "abort"(0xaaaab86a6890) to PLT(base + 0x8a0)
mcount: mcount setup done   
★ Hang up here
```

**Comment by leimaohui** [comment]
[Uploading a-cpp.out.txt…]()

**Comment by leimaohui** [comment]
[Uploading a-cpp.out.txt…]()

**Comment by namhyung** [comment]
Thanks for the information and your work.  Indeed, I found the .plt section header misses the entry size.  It seems resolved addresses are wrong.  I'll take a look at it, thanks!

**Comment by honggyukim** [comment]
@leimaohui Thanks for your analysis. I have summarized this problem in #1254. uftrace is broken even for a very simple program.

**Comment by namhyung** [comment]
@leimaohui Could you please test it with plt_entsize change only (IOW reverting the PLT0 size change)?  It seems it detect differences between resolved address and plt resolver address but it's because you changed the size.

**Comment by honggyukim** [comment]
@namhyung Do you mean by this change?
```diff
diff --git a/utils/symbol.c b/utils/symbol.c
index 29a1d295..01e52dab 100644
--- a/utils/symbol.c
+++ b/utils/symbol.c
@@ -560,6 +560,7 @@ int load_elf_dynsymtab(struct symtab *dsymtab, struct uftrace_elf_data *elf,
        }
        else if (elf->ehdr.e_machine == EM_AARCH64) {
                plt_addr += 16;    /* AARCH64 PLT0 size is 32 */
+               plt_entsize = 16;
        }
        else if (elf->ehdr.e_machine == EM_386) {
                plt_entsize += 12;
```
It works fine in aarch64 Ubuntu 20.10. I also need to test it in aarch64 Ubuntu 20.04 as well.
```
$ gcc -pg -o t-abc tests/s-abc.c

$ uftrace t-abc
# DURATION     TID     FUNCTION
   1.708 us [  8168] | __monstartup();
   0.125 us [  8168] | __cxa_atexit();
            [  8168] | main() {
            [  8168] |   a() {
            [  8168] |     b() {
            [  8168] |       c() {
   0.375 us [  8168] |         getpid();
   1.375 us [  8168] |       } /* c */
   1.792 us [  8168] |     } /* b */
   2.083 us [  8168] |   } /* a */
   2.417 us [  8168] | } /* main */
```

**Comment by honggyukim** [comment]
The above change doesn't break aarch64 Ubuntu 20.04 as well.

**Comment by namhyung** [comment]
Sorry for the late reply.

@honggyukim yes something like that.  But actually I want to check if it's zero first.

@leimaohui can you please confirm the above fixes your problem?

**Comment by namhyung** [comment]
Please go ahead! :)

**Comment by honggyukim** [comment]
@leimaohui Could you please reopen this PR? We have discussion history in this PR. :)

I also would like to ask you to write more description in the commit message. Please read other commit messages with `git log`.

**Comment by honggyukim** [comment]
For example, the commit message can be like
```
aarch64: Fix a plthook crash on aarch64 with binutils2.35.1 and later versions

plthook is always crashed in Ubuntu 20.10 aarch64, which uses binutils 2.35.1.
Since the `plt_entsize` is not automatically set in this version, we have to
explicitly set the value.

This patch fixes the following problem.

  $ uname -m
  aarch64

  $ cat /etc/os-release | grep PRETTY_NAME
  PRETTY_NAME="Ubuntu 20.10"

  $ gcc -pg tests/s-abc.c

  $ uftrace record a.out
  WARN: child terminated by signal: 7: Bus error

Fixed: #1254

Signed-off-by: Lei Maohui <leimaohui@cn.fujitsu.com>
```

**Comment by leimaohui** [comment]
I'm sorry, this PR is closed just because I reset my repository and submit a new PR(https://github.com/namhyung/uftrace/pull/1256).
It seems that this PR can't be reopen...

**Comment by honggyukim** [comment]
I'm not sure but https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c may work. But if you don't feel comfortable, then please go ahead in a new PR then.

**Pull request closed without merging**
