### PR TITLE
doc: Fix tutorial slide (fixes #1472)

### LINKED ISSUE #1472: tutorial slide missing record command in task graph page
Our tutorial slide has a bug in https://uftrace.github.io/slide/#108.

It says
```
    $ uftrace --force /usr/bin/gcc hello.c
    $ uftrace graph --task
    ========== TASK GRAPH ==========
    # TOTAL TIME   SELF TIME     TID     TASK NAME
      159.854 ms    4.440 ms  [ 82723] : gcc
                                       :  |
       90.951 ms   90.951 ms  [ 82734] :  +----cc1
                                       :  |
       17.150 ms   17.150 ms  [ 82735] :  +----as
                                       :  |
       45.183 ms    6.076 ms  [ 82736] :  +----collect2
                                       :        |
       38.880 ms   38.880 ms  [ 82737] :        +----ld
```
But the first command has to be
```
    $ uftrace record --force /usr/bin/gcc hello.c
```
It needs to be fixed at https://github.com/namhyung/uftrace/blob/v0.12/doc/uftrace.html#L2055-L2084.

Please note that it won't be shown at https://uftrace.github.io/slide until the change is applied to https://github.com/uftrace/uftrace.github.io/blob/master/slide/uftrace.html.

### PR DESCRIPTION
**Pull request by valdaarhun**
Fixes #1472

Signed-off-by: Sahil Siddiq <icegambit91@gmail.com>

### CODE REVIEW

**Comment by honggyukim** [comment]
Hi @valdaarhun, thanks for the PR. But could you please update the commit message as follows?
```
doc: Fix tutorial slide

Fixed: #1472 
Signed-off-by: Sahil Siddiq icegambit91@gmail.com
```
The message in GitHub is written but your commit message is empty now.

**Comment by valdaarhun** [comment]
Done.

**Comment by honggyukim** [comment]
Ah.. sorry email should be
```
Signed-off-by: Sahil Siddiq <icegambit91@gmail.com>
```
But never mind if you don't want to update again.

**Comment by valdaarhun** [comment]
No worries. I have corrected it now.

**Review by namhyung — APPROVED** [review]
LGTM

**Pull request merged**
