### PR TITLE
tests: Fix IndexError by checking report length

### PR DESCRIPTION
**Pull request by jonghyeon-an**
Similar to issue #1509, sometimes TC 125 raised an IndexError with an abnormal output.
IndexError interferes with test normality, so I try to solve it with this PR.

- test normality even when abnormal results are output
- remove the code that checks for empty lines
- remove try...catch code with length check
- resolve pylint: No exception type (W0702:bare-except)

### Additional debugging code and abnormal results
- Missing self time value

```
$ git diff
diff --git a/tests/runtest.py b/tests/runtest.py
index dfe39dfd..991443c5 100755
--- a/tests/runtest.py
+++ b/tests/runtest.py
@@ -334,6 +334,7 @@ class TestBase:
         """ This function post-processes output of the test to be compared .
             It ignores blank and comment (#) lines and remaining functions.  """
         result = []
+        print (output)
         for ln in output.split('\n'):
             if ln.strip() == '':
                 continue

$ ./runtest.py -vdp -O0 125
Start 1 tests without worker pool
Test case                 pg
------------------------: O0
build command: gcc -o t-abc -fno-inline -fno-builtin -fno-ipa-cp -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0  -pg -O0  s-abc.c
prerun command: /home/user/uftrace/uftrace record --no-pager --no-event --libmcount-path=/home/user/uftrace  t-abc
prerun command: /home/user/uftrace/uftrace replay --no-pager --no-event --libmcount-path=/home/user/uftrace -f time -F main t-abc
test command: /home/user/uftrace/uftrace report --no-pager --no-event --libmcount-path=/home/user/uftrace -F main -r ~920.260799000 t-abc

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================================
    2.160 us    0.172 us           1  main
    1.988 us    0.126 us           1  a
    1.862 us    0.375 us           1  b
    1.487 us    0.747 us           1  c
    0.740 us    0.740 us           1  getpid

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    1.200 us    0.100 us           1  main
    1.100 us    0.100 us           1  a
    1.000 us                       1  b
    1.000 us    0.400 us           1  c
    0.600 us    0.600 us           1  getpid

Traceback (most recent call last):
  File "./runtest.py", line 906, in <module>
    results = run_single_case(name, flags, opts.split(), arg)
  File "./runtest.py", line 707, in run_single_case
    ret, dif = tc.run(case, cflags, arg.diff, timeout)
  File "/home/user/uftrace/tests/runtest.py", line 579, in run
    result_tested = self.sort(result_origin)  # for python3
  File "/home/user/uftrace/tests/runtest.py", line 452, in sort
    return func(self, output, ignore_children)
  File "/home/user/uftrace/tests/runtest.py", line 354, in report_sort
    result.append('%s %s' % (line[4], line[5]))
IndexError: list index out of range
```

### After changes
```
$ ./runtest.py -vdp -O0 125
Start 1 tests without worker pool
Test case                 pg
------------------------: O0
build command: gcc -o t-abc -fno-inline -fno-builtin -fno-ipa-cp -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0  -pg -O0  s-abc.c
prerun command: /home/user/uftrace/uftrace record --no-pager --no-event --libmcount-path=/home/user/uftrace  t-abc
prerun command: /home/user/uftrace/uftrace replay --no-pager --no-event --libmcount-path=/home/user/uftrace -f time -F main t-abc
test command: /home/user/uftrace/uftrace report --no-pager --no-event --libmcount-path=/home/user/uftrace -F main -r ~1319.892205200 t-abc

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================================
    2.160 us    0.172 us           1  main
    1.988 us    0.126 us           1  a
    1.862 us    0.375 us           1  b
    1.487 us    0.747 us           1  c
    0.740 us    0.740 us           1  getpid

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    2.000 us    0.200 us           1  main
    1.800 us    0.200 us           1  a
    1.600 us                       1  b
    1.600 us    1.000 us           1  c
    0.600 us    0.600 us           1  getpid

=========== original ===========
  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    2.000 us    0.200 us           1  main
    1.800 us    0.200 us           1  a
    1.600 us                       1  b
    1.600 us    1.000 us           1  c
    0.600 us    0.600 us           1  getpid

===========  result  ===========
1 main
1 a
1 c
1 getpid
=========== expected ===========
1 main
1 a
1 b
1 c
1 getpid

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================================
    2.160 us    0.172 us           1  main
    1.988 us    0.126 us           1  a
    1.862 us    0.375 us           1  b
    1.487 us    0.747 us           1  c
    0.740 us    0.740 us           1  getpid

t125_report_range: diff result of -pg -O0
--- expect      2022-08-15 22:04:29.653448200 +0900
+++ result      2022-08-15 22:04:29.653448200 +0900
@@ -2,3 +2,2 @@
 1 a
-1 b
 1 c

125 report_range        : NG
```

### CODE REVIEW

**Review by namhyung — COMMENTED** [review]
Thanks for the fix.  But it's unfortunate that the test remains failed.  How about reading such lines and accessing the fields using negative indices like -1 and -2?

**Comment by jonghyeon-an** [comment]
> Thanks for the fix. But it's unfortunate that the test remains failed. How about reading such lines and accessing the fields using negative indices like -1 and -2?

Thanks for the comment.

As you suggested, I can change it to -2 and -1 to fix IndexError and OK, but I thought that NG handling is more appropriate for abnormal format as above output.

```
result. append('%s %s' % (line[4], line[5])) # before
result. append('%s %s' % (line[-2], line[-1])) # after
```

So, is it ok to treat these test cases as OK?

**Comment by namhyung** [comment]
I think the proper fix is to have an option not to skip printing time even if it's 0 and use it for the test.  But I'm not sure it's really needed.  This is just because some platform (like in a VM) doesn't provide a good clock resolution.  In the normal (native) Linux system, I think we won't see the kind of problem.

**Comment by jonghyeon-an** [comment]
> I think the proper fix is to have an option not to skip printing time even if it's 0 and use it for the test. But I'm not sure it's really needed. This is just because some platform (like in a VM) doesn't provide a good clock resolution. In the normal (native) Linux system, I think we won't see the kind of problem.

Oh I see. Then, I'll close the PR, considering that the patch to fix the IndexError is not needed.

**Comment by namhyung** [comment]
No, I don't mean it.  Please fix the test failure with negative index.

**Comment by jonghyeon-an** [comment]
> No, I don't mean it. Please fix the test failure with negative index.

I misunderstood.
OK, I'll fix the append function to access it with a negative index.

```
- result.append('%s %s' % (line[4], line[5]))
+ result.append('%s %s' % (line[-2], line[-1]))
```

**Comment by jonghyeon-an** [comment]
### After changes

```
$ ./runtest.py -vdp -O0 125
Start 1 tests without worker pool
Test case                 pg
------------------------: O0
build command: gcc -o t-abc -fno-inline -fno-builtin -fno-ipa-cp -fno-omit-frame-pointer -D_FORTIFY_SOURCE=0  -pg -O0  s-abc.c
prerun command: /home/user/uftrace/uftrace record --no-pager --no-event --libmcount-path=/home/user/uftrace  t-abc
prerun command: /home/user/uftrace/uftrace replay --no-pager --no-event --libmcount-path=/home/user/uftrace -f time -F main t-abc
test command: /home/user/uftrace/uftrace report --no-pager --no-event --libmcount-path=/home/user/uftrace -F main -r ~400.363649500 t-abc

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================================
    2.160 us    0.172 us           1  main
    1.988 us    0.126 us           1  a
    1.862 us    0.375 us           1  b
    1.487 us    0.747 us           1  c
    0.740 us    0.740 us           1  getpid

  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    1.900 us    0.200 us           1  main
    1.700 us    0.200 us           1  a
    1.500 us                       1  b
    1.500 us    1.000 us           1  c
    0.500 us    0.500 us           1  getpid

=========== original ===========
  Total time   Self time       Calls  Function
  ==========  ==========  ==========  ====================
    1.900 us    0.200 us           1  main
    1.700 us    0.200 us           1  a
    1.500 us                       1  b
    1.500 us    1.000 us           1  c
    0.500 us    0.500 us           1  getpid

===========  result  ===========
1 main
1 a
1 b
1 c
1 getpid
=========== expected ===========
1 main
1 a
1 b
1 c
1 getpid
125 report_range        : OK
```

**Comment by jonghyeon-an** [comment]
> Would be nice to have some more explanation in the commit message like below:
> 
> > This is just because some platform (like in a VM) doesn't provide a good clock resolution. In the normal (native) Linux system, I think we won't see the kind of problem.

As you suggested, I added the explanation to the commit message.

> This happened because some platforms, like VM or WSL2, don't provide good clock resolution.

**Review by namhyung — APPROVED** [review]
LGTM

**Comment by jonghyeon-an** [comment]
Now I know. This same issue was registered as #1522.

**Pull request merged**
