### PR TITLE
New release v0.11

### PR DESCRIPTION
**Pull request by namhyung**
I'm preparing v0.11 release.  Please test it!

### CODE REVIEW

**Comment by honggyukim** [comment]
The current `x86_64` test result is as follows.
```
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
117 time_range          : NG OK OK OK NG OK OK OK OK OK    # random failures
125 report_range        : OK NG OK OK OK NG OK OK OK OK    # random failures
135 trigger_time2       : OK OK OK OK OK OK OK NG OK OK    # random failures
151 recv_runcmd         : NG NG NG NG NG NG NG NG NG NG
162 pltbind_now_pie     : BI BI BI BI BI BI BI BI BI BI
182 thread_exit         : OK NG OK OK NG OK OK OK OK NG
202 arg_dwarf2          : OK OK NG NG NG SK SK SK SK SK
203 arg_dwarf3          : OK OK NG NG NG SK SK SK SK SK
204 arg_dwarf4          : OK OK NG NG OK SK SK SK SK SK
222 external_data       : OK OK OK OK NG OK OK OK NG OK    # random failures
248 dynamic_dlopen      : OK OK OK OK NG OK OK OK OK NG
251 exception4          : NG NG NG NG NG NG NG NG NG NG
```

**Comment by honggyukim** [comment]
Here is the result in aarch64 but with clang to avoid argument failures. I also removed PMU tests because I tested it on M1 Mac with parallels.
```
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
012 demangle            : OK OK OK OK OK OK OK NG OK OK
014 ucontext            : OK NG NG NG NG OK OK OK OK OK
015 longjmp             : OK NG NG NG NG OK OK OK OK OK
048 malloc_impl         : TM TM TM TM TM OK OK OK OK OK
062 arg_char            : OK NG NG NG NG SK SK SK SK SK
082 arg_many            : NG NG NG NG NG SK SK SK SK SK
083 arg_float           : OK NG NG NG NG SK SK SK SK SK
084 arg_mixed           : NG SG SG SG SG SK SK SK SK SK
085 arg_reg             : NG SG SG SG SG SK SK SK SK SK
086 arg_stack           : NG NG NG NG NG SK SK SK SK SK
090 report_recursive    : OK NG NG NG NG OK OK OK OK OK
117 time_range          : OK OK NG OK OK OK OK OK OK OK
124 exception           : OK OK OK OK OK NG NG NG NG NG
125 report_range        : OK OK OK OK NG OK OK OK OK OK
140 dynamic_xray        : NG NG NG NG NG NG NG NG NG NG
146 arg_std_string      : NG OK NG NG NG SK SK SK SK SK
151 recv_runcmd         : NG NG NG NG NG NG NG NG NG NG
162 pltbind_now_pie     : OK OK OK OK OK BI BI BI BI BI
185 exception2          : OK OK OK OK OK NG NG NG NG NG
186 exception3          : OK OK SG SG SG NG NG NG NG NG
201 arg_dwarf1          : OK NG NG NG NG SK SK SK SK SK
202 arg_dwarf2          : NG OK OK OK OK SK SK SK SK SK
203 arg_dwarf3          : NG SG SG SG SG SK SK SK SK SK
204 arg_dwarf4          : OK NG NG NG NG SK SK SK SK SK
205 arg_auto4           : NG NG NG NG NG SK SK SK SK SK
208 watch_cpu           : OK OK OK OK OK OK OK OK NG OK
214 signal_trigger      : OK OK OK OK OK NZ NZ NZ NZ NZ
222 external_data       : OK OK OK OK NG OK OK OK OK OK
225 dynamic_size        : NG OK OK OK NG NG OK OK OK NG
231 arg_bound           : OK OK OK OK NG SK SK SK SK SK
248 dynamic_dlopen      : OK OK NG NG NG OK OK NG NG NG
251 exception4          : NG NG NG NG NG SG SG SG SG SG
254 arg_dwarf5          : NG NZ NZ NZ NZ SK SK SK SK SK
255 arg_dwarf6          : NG NG NG NG NG SK SK SK SK SK
```

**Comment by honggyukim** [comment]
`i386` test result is here.
```
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
012 demangle            : NG NG NG NG NG NG NG NG NG NG
025 report_s_call       : OK NG OK OK OK OK OK OK OK OK
043 full_demangle       : NG NG NG NG NG NG NG NG NG NG
122 time_range2         : NG NG NG OK NG OK OK OK OK OK
124 exception           : NG NG NG NG NG NG NG NG NG NG
125 report_range        : OK NG OK OK OK NG OK OK OK OK
134 pic_pie             : OK OK OK OK OK NG NG NG NG NG
140 dynamic_xray        : BI BI BI BI BI BI BI BI BI BI
147 event_sdt           : BI BI BI BI BI BI BI BI BI BI
150 recv_event          : BI BI BI BI BI BI BI BI BI BI
151 recv_runcmd         : NG NG NG NG NG NG NG NG NG NG
161 pltbind_now         : NG NG NG NG NG NG NG NG NG NG
162 pltbind_now_pie     : NG NG NG NG NG NG NG NG NG NG
164 report_sched        : OK OK OK OK OK OK OK OK NG OK
182 thread_exit         : OK NG OK NG NG OK OK OK OK OK
212 noplt_libcall       : NG NG NG NG NG NG NG NG NG NG
220 trace_script        : NG NG NG NG NG NG NG NG NG NG
222 external_data       : OK OK OK OK OK OK OK OK NG OK
251 exception4          : NG NG NG NG NG NG NG NG NG NG
```

**Comment by namhyung** [comment]
Thanks for sharing.  I'm not worrying too much about the random failures for now, but we should take a look if it keeps happening.

**Comment by honggyukim** [comment]
I'm also fine ignoring random failures because that's only the problem of testing itself. I will take more about each test when I have time. I'm also fine to make a release if we don't have horrible regressions.

**Comment by namhyung** [comment]
Added bug fix entries to the NEWS.

**Comment by honggyukim** [comment]
Thanks. I’m fine to make a thanks giving day release then :)

**Comment by namhyung** [comment]
@AmeyaVS thanks for the report.  I found a bug in the change you mentioned.  It won't run checks when you build out of tree and the check was run in-tree before.  Will fix it with the following patch.

```diff
diff --git a/check-deps/Makefile b/check-deps/Makefile
index 1b5f3304..56031ebf 100644
--- a/check-deps/Makefile
+++ b/check-deps/Makefile
@@ -52,10 +52,10 @@ CFLAGS_have_libunwind  = $(shell pkg-config --cflags libunwind 2> /dev/null)
 LDFLAGS_have_libunwind = $(shell pkg-config --libs   libunwind 2> /dev/null)
 CFLAGS_cc_has_minline_all_stringops = -minline-all-stringops
 
-check-build: $(CHKDIR)/check-tstamp $(CHECK_LIST)
+check-build: $(CHECK_LIST)
 
-$(CHECK_LIST): %: __%.c
-       @$(CC) $(CHECK_CFLAGS) -o $(CHKDIR)/$@  $< $(CHECK_LDFLAGS) > /dev/null 2>&1
+$(CHECK_LIST): %: __%.c $(CHKDIR)/check-tstamp
+       $(CC) $(CHECK_CFLAGS) -o $(CHKDIR)/$@  $< $(CHECK_LDFLAGS) > /dev/null 2>&1
 
 $(CHKDIR)/check-tstamp: PHONY
        @mkdir -p $(dir $@)
```

**Comment by namhyung** [comment]
> Will fix it with the following patch.

Done.

**Pull request merged**
