### PR TITLE
Naming convention of the C++ language standard.

### PR DESCRIPTION
**Pull request by qpakzk**
I solved #187 a little bit.
I changed to naming convention of the C++ language standard in uftrace.h file and utils/utils.h file.

### CODE REVIEW

**Comment by namhyung** [comment]
Thanks, but could you please do it for the all header files in a single commit?

**Comment by qpakzk** [comment]
OK! I made one commit.
By the way, do you want to change all header files in the uftrace project like #187 .

**Comment by namhyung** [comment]
Yes, please!

**Comment by qpakzk** [comment]
I edited all header files in uftrace project.

**Comment by qpakzk** [comment]
By @elfring 's advice, I try to make the commit message detail.

**Comment by qpakzk** [comment]
I found some #endifs have comments like [acknowleding what it is matched with](https://github.com/namhyung/uftrace/blob/master/uftrace.h#L514), but [others don't have them](https://github.com/namhyung/uftrace/blob/master/libtraceevent/event-utils.h#L81).

Would you(@namhyung) mind adding comments next to #endifs?

**Comment by namhyung** [comment]
As I said in other issue, please remove the changes in libtraceevent/, utils/list.h and utils/rbtree.h.  Otherwise, looks good to me.  Thanks!

**Comment by qpakzk** [comment]
I removed the changes in libtraceevent/, utils/list.h and utils/rbtree.h.

**Pull request merged**
